schema = 1
id = "lv2.gxluna"
name = "GxLuna"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "GxPlugins"
tags = ["Distortion"]
description = "Gnarly overdrive pedal simulation."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxluna/1.0.0.zip"
sha256 = "47af09397908fd4516f5fd3cc95b955a0f3194d03065c03c5ae32d7ed2f4eef0"
size = 829973

[install]
entry = "GxLuna.lv2/manifest.ttl"
