schema = 1
id = "jsfx.jozmac.jm-fx-stft-stereoscope-eq"
name = "JM_fx_STFT_Stereoscope_EQ"
version = "1.0"
format = "jsfx"
arch = ["arm64-v8a"]
manufacturer = "Jozef Mackowiak"
source = "https://github.com/jozmac/reapack-jm"
tags = ["Analyzer","EQ","Stereo"]
description = "A spectral stereo analysis and EQ tool for inspecting and shaping frequency content across channels."
license = "custom"

[payload]
kind = "files"
size = 31731

[[payload.files]]
url = "https://raw.githubusercontent.com/jozmac/reapack-jm/4f507485554c90dcb6a3670058a8f4812c851518/Effects/JM_fx_STFT_Stereoscope_EQ.jsfx"
sha256 = "062afc05bd9cc06c8ea2961926de571e828e7d1479ced3af9d43ca93c42b4085"
size = 23099
path = "JM_fx_STFT_Stereoscope_EQ.jsfx"

[[payload.files]]
url = "https://raw.githubusercontent.com/jozmac/reapack-jm/4f507485554c90dcb6a3670058a8f4812c851518/ThirdParty/Tale/complex.jsfx-inc"
sha256 = "73c92fd28398fdabb4dfecf592e910876dcc7392b9f4c11dfe44a0fda1fa28eb"
size = 8632
path = "Tale/complex.jsfx-inc"

[install]
entry = "JM_fx_STFT_Stereoscope_EQ.jsfx"
