schema = 1
id = "lv2.gxdop250"
name = "GxDOP250"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "GxPlugins"
tags = ["Distortion"]
description = "Overdrive Preamp Pedal simulation."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxdop250/1.0.0.zip"
sha256 = "7ada51e1eb8ba120321670d991e06642b73b8576670784e6683ca457771b51c9"
size = 1244364

[install]
entry = "GxDOP250.lv2/manifest.ttl"
