schema = 1
id = "lv2.gxplexi"
name = "GxPlexi"
version = "1.0.0"
format = "lv2"
arch = ["arm64-v8a"]
manufacturer = "GxPlugins"
tags = ["Amplifier"]
description = "Power Amp simulation."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxplexi/1.0.0.zip"
sha256 = "61c0eaf5cdf9c7b41f8beaa754963ba8893ebe72e75e445d8cb4d663b4a781ba"
size = 846967

[install]
entry = "GxPlexi.lv2/manifest.ttl"
