schema = 1
id = "jsfx.tilr.quickdist"
name = "quickdist.jsfx"
version = "1.0.1"
format = "jsfx"
arch = ["arm64-v8a"]
manufacturer = "tilr"
tags = ["jsfx"]
description = "QuickDist"
license = "custom"

[payload]
kind = "files"
size = 133708

[[payload.files]]
url = "https://raw.githubusercontent.com/tiagolr/tilr_jsfx/7d4f4a68e4c9041414127b2c058e4e6229b9346a/Distortion/quickdist.jsfx"
sha256 = "4a0832061b0f4e19bb218fa6cf655bc2a456f211b5347a3249138ad48b0cfd1e"
size = 5679
path = "quickdist.jsfx"

[[payload.files]]
url = "https://raw.githubusercontent.com/tiagolr/tilr_jsfx/7d4f4a68e4c9041414127b2c058e4e6229b9346a/Distortion/qdist/qdist.squashman_upsamplers.jsfx-inc"
sha256 = "ceb2766663f082fbbdb78c9fe33c21001afb744f613ec19c9bc8241cc3769902"
size = 128029
path = "qdist/qdist.squashman_upsamplers.jsfx-inc"

[install]
entry = "quickdist.jsfx"
