schema = 1
id = "lv2.gxshimmizita"
name = "gx_shimmizita"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "Guitarix"
tags = ["Reverb","Pitch"]
description = "gx_shimmizita combines reverberant ambience with pitch-shifted shimmer for an elevated, spacious tail."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxshimmizita/1.0.0.zip"
sha256 = "82f4a12a21d242e6082a3dce2bcf72c290c37d6b0a363e99733b299f84c7993c"
size = 4866839

[install]
entry = "gx_shimmizita.lv2/manifest.ttl"
