schema = 1
id = "jsfx.tilr.albeton-autopan"
name = "Albeton - Autopan.jsfx"
version = "1.0.0"
format = "jsfx"
arch = ["arm64-v8a"]
manufacturer = "tilr"
tags = ["jsfx"]
description = "Albeton - Autopan"
license = "custom"

[payload]
kind = "files"
size = 6651

[[payload.files]]
url = "https://raw.githubusercontent.com/tiagolr/tilr_jsfx/228ee2e902dd448478cc7723db49242e1cc39301/Modulation/Albeton%20-%20Autopan.jsfx"
sha256 = "36d5239978342bc727e13becaed7d33749523916eb0a9173e3ca907583fc04ca"
size = 6651
path = "Albeton - Autopan.jsfx"

[install]
entry = "Albeton - Autopan.jsfx"
