schema = 1
id = "jsfx.tukan.violet-envelope-shaper-s2"
name = "Violet Envelope Shaper S2 (Tukan).jsfx"
version = "1.0.0"
format = "jsfx"
arch = ["arm64-v8a"]
manufacturer = "TukanStudios"
tags = ["jsfx"]
description = "Violet Envelope Shaper S2 (Tukan)"
license = "custom"

[payload]
kind = "files"
size = 64361

[[payload.files]]
url = "https://raw.githubusercontent.com/TukanStudios/TUKAN_STUDIOS_PLUGINS/e400035bb4c02bf95c1adbef803cba2e4b6b36b5/Violet%20Envelope%20Shaper%20S2%20(Tukan)"
sha256 = "43cbed0b94f37e5bb3e9d7f37f15ab308a7612191f7c1217d3f3c73756f2b554"
size = 31185
path = "Violet Envelope Shaper S2 (Tukan).jsfx"

[[payload.files]]
url = "https://raw.githubusercontent.com/TukanStudios/TUKAN_STUDIOS_PLUGINS/e400035bb4c02bf95c1adbef803cba2e4b6b36b5/S2GFX/tk_lib.jsfx-inc"
sha256 = "9033bfcdf5e60a8805484837faa0138519ae14e1f29a3c773993f6209bc49754"
size = 33176
path = "S2GFX/tk_lib.jsfx-inc"

[install]
entry = "Violet Envelope Shaper S2 (Tukan).jsfx"
