schema = 1
id = "jsfx.sonic.bass-professor-mark-ii"
name = "Bass Professor Mark II"
version = "1.0"
format = "jsfx"
arch = ["arm64-v8a"]
manufacturer = "SonicAnomaly"
source = "https://github.com/Sonic-Anomaly/Sonic-Anomaly-JSFX"
tags = ["Saturation"]
description = "Bass Professor Mark II enhances bass with saturation, adding harmonic weight and greater presence."
license = "custom"

[payload]
kind = "files"
size = 507118

[[payload.files]]
url = "https://raw.githubusercontent.com/Sonic-Anomaly/Sonic-Anomaly-JSFX/f14cef59b86bd58c3e1e6a5bf982ff71c302443f/Plugins/Bass%20Professor%20Mark%20II.jsfx"
sha256 = "2fdee86d5981ef527b2d9969e39ad286528dc9fd3f3e7113058e401cf7bd0ef1"
size = 16794
path = "Bass Professor Mark II.jsfx"

[[payload.files]]
url = "https://raw.githubusercontent.com/Sonic-Anomaly/Sonic-Anomaly-JSFX/f14cef59b86bd58c3e1e6a5bf982ff71c302443f/Plugins/bassprofessormk2_gfx/bg.png"
sha256 = "eab20d7b5c721c66dde3f183d84b99f9406676a1a46231f40e1f3c3a7331bae5"
size = 173637
path = "bassprofessormk2_gfx/bg.png"

[[payload.files]]
url = "https://raw.githubusercontent.com/Sonic-Anomaly/Sonic-Anomaly-JSFX/f14cef59b86bd58c3e1e6a5bf982ff71c302443f/Plugins/bassprofessormk2_gfx/vsliderhandle.png"
sha256 = "e1cb0985016622ea1d9607367b80bd0a89dfa6a8e323a743566d9916b0225331"
size = 266
path = "bassprofessormk2_gfx/vsliderhandle.png"

[[payload.files]]
url = "https://raw.githubusercontent.com/Sonic-Anomaly/Sonic-Anomaly-JSFX/f14cef59b86bd58c3e1e6a5bf982ff71c302443f/Plugins/docs/Bass%20Professor%20Mark%20II.pdf"
sha256 = "ec447df7bfbdd322f919c7eb93bae116e82366373c104a9bba23bd5910c6ebf2"
size = 316421
path = "docs/Bass Professor Mark II.pdf"

[install]
entry = "Bass Professor Mark II.jsfx"
