schema = 1
id = "lv2.gxvoodofuzz"
name = "GxVoodoFuzz"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "GxPlugins"
tags = ["Distortion"]
description = "Fuzz, tone shaping, and boost."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxvoodofuzz/1.0.0.zip"
sha256 = "3bf4d731214a801a058bba0db19f804bd0bc71ae10b40980c208119fec4cbcfd"
size = 1460078

[install]
entry = "GxVoodoFuzz.lv2/manifest.ttl"
