schema = 1
id = "lv2.gxmetalhead"
name = "gxmetal_head"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "Guitarix"
tags = ["Amplifier","Distortion"]
description = "gxmetal_head supplies a high-gain amplifier-head sound for aggressive, harmonically dense guitar tones."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxmetalhead/1.0.0.zip"
sha256 = "fdb516e56bfcb45a14facef396204c0a3c6530dd501dae08567204db32acb753"
size = 4226762

[install]
entry = "gxmetal_head.lv2/manifest.ttl"
