schema = 1
id = "jsfx.joep.saike-smooth"
name = "saike_smooth"
version = "0.05"
format = "jsfx"
arch = ["arm64-v8a"]
manufacturer = "Joep Vanlier"
source = "https://github.com/JoepVanlier/JSFX"
tags = ["Utility","Dynamics"]
description = "saike_smooth reduces abrupt signal variation to produce gentler, more continuous changes."
license = "custom"

[payload]
kind = "files"
size = 4325

[[payload.files]]
url = "https://raw.githubusercontent.com/JoepVanlier/JSFX/53560d66cf4608658d305f569012eb2d43341246/Basics/saike_smooth.jsfx"
sha256 = "ab8a7194678770c3b73aa3e53feb78c7140c4bf43c2c5b25a30057ef6af1e816"
size = 4325
path = "saike_smooth.jsfx"

[install]
entry = "saike_smooth.jsfx"
