schema = 1
id = "lv2.preampimpulses"
name = "PreAmpImpulses"
version = "1.0.0"
format = "lv2"
arch = ["arm64-v8a"]
manufacturer = "brummer10"
tags = ["Mixer"]
description = "Mixer/routing utility."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.preampimpulses/1.0.0.zip"
sha256 = "b1e04e42ec361c99ecd395132c382ffcb49cc0df9ac6d5f9bc5fc7d8002f7f91"
size = 2925594

[install]
entry = "PreAmpImpulses.lv2/manifest.ttl"
