schema = 1
id = "jsfx.tilr.qdelay"
name = "qdelay.jsfx"
version = "1.0.5"
format = "jsfx"
arch = ["arm64-v8a"]
manufacturer = "tilr"
tags = ["jsfx"]
description = "QDelay"
license = "custom"

[payload]
kind = "files"
size = 53841

[[payload.files]]
url = "https://raw.githubusercontent.com/tiagolr/tilr_jsfx/b85ae1282b097feb6873f1417a668b73690067ca/Delay/qdelay.jsfx"
sha256 = "831c8f27f28ba8f35b130a8870cd6d31beaa3e8337a99430381d712fc8f9ba63"
size = 12578
path = "qdelay.jsfx"

[[payload.files]]
url = "https://raw.githubusercontent.com/tiagolr/tilr_jsfx/b85ae1282b097feb6873f1417a668b73690067ca/Delay/qdelay2/qd2.delay.jsfx-inc"
sha256 = "ce3326988143007f20dd495145e4fe073dfcf92aa8dd5fd7ab74b9f80219100e"
size = 17528
path = "qdelay2/qd2.delay.jsfx-inc"

[[payload.files]]
url = "https://raw.githubusercontent.com/tiagolr/tilr_jsfx/b85ae1282b097feb6873f1417a668b73690067ca/Delay/qdelay2/qd2.rbj_filter.jsfx-inc"
sha256 = "7a5885bb0c1523856ac682a9fc9a499c3a9de12d7b87837664f9e4ffefbc341b"
size = 9422
path = "qdelay2/qd2.rbj_filter.jsfx-inc"

[[payload.files]]
url = "https://raw.githubusercontent.com/tiagolr/tilr_jsfx/b85ae1282b097feb6873f1417a668b73690067ca/Delay/qdelay2/qd2.saike_pitchlib.jsfx-inc"
sha256 = "07dd4fbdc5b276237aed10b3f5c3bb1ae97e7894f56826280f593dc2c489524b"
size = 9823
path = "qdelay2/qd2.saike_pitchlib.jsfx-inc"

[[payload.files]]
url = "https://raw.githubusercontent.com/tiagolr/tilr_jsfx/b85ae1282b097feb6873f1417a668b73690067ca/Delay/qdelay2/qd2.gfxlib.jsfx-inc"
sha256 = "1051342c583031538e8b5eaa0fece4b387d3d2e67753113058ecdfbe37d9b43a"
size = 4490
path = "qdelay2/qd2.gfxlib.jsfx-inc"

[install]
entry = "qdelay.jsfx"
