schema = 1
id = "jsfx.tilr.tinyrec"
name = "tinyrec.jsfx"
version = "1.0.3"
format = "jsfx"
arch = ["arm64-v8a"]
manufacturer = "tilr"
tags = ["jsfx"]
description = "TinyRec"
license = "custom"

[payload]
kind = "files"
size = 23184

[[payload.files]]
url = "https://raw.githubusercontent.com/tiagolr/tilr_jsfx/9f965d532fb1b55711f98f211fa2a65ed49eea7a/Utility/tinyrec.jsfx"
sha256 = "dc49cb5aba0fb827fdd67dfa0772453f1fec21489a85cbd8b97fbbe12ff5385a"
size = 14129
path = "tinyrec.jsfx"

[[payload.files]]
url = "https://raw.githubusercontent.com/tiagolr/tilr_jsfx/9f965d532fb1b55711f98f211fa2a65ed49eea7a/Utility/tinyrec/tr.gfxlib.jsfx-inc"
sha256 = "4001fa1af63d2f6f7a7d35ea596f134d47963ef14b613263d155d0baa6e62209"
size = 1322
path = "tinyrec/tr.gfxlib.jsfx-inc"

[[payload.files]]
url = "https://raw.githubusercontent.com/tiagolr/tilr_jsfx/9f965d532fb1b55711f98f211fa2a65ed49eea7a/Utility/tinyrec/img/loop_active.png"
sha256 = "4c69c5b2c07d37bf4f4274bf9a711040a769db17d1c4d0492ef15379a7b5ba1c"
size = 915
path = "tinyrec/img/loop_active.png"

[[payload.files]]
url = "https://raw.githubusercontent.com/tiagolr/tilr_jsfx/9f965d532fb1b55711f98f211fa2a65ed49eea7a/Utility/tinyrec/img/loop.png"
sha256 = "019a5902d3116f8a5e8b3d566739d5e3e194c6c53e18b3058d222e70efc0d4cf"
size = 1070
path = "tinyrec/img/loop.png"

[[payload.files]]
url = "https://raw.githubusercontent.com/tiagolr/tilr_jsfx/9f965d532fb1b55711f98f211fa2a65ed49eea7a/Utility/tinyrec/img/pause.png"
sha256 = "0e31f15288710b0c8ad979463eaa2fcd9094055a496073bc391117af4a142adc"
size = 562
path = "tinyrec/img/pause.png"

[[payload.files]]
url = "https://raw.githubusercontent.com/tiagolr/tilr_jsfx/9f965d532fb1b55711f98f211fa2a65ed49eea7a/Utility/tinyrec/img/play.png"
sha256 = "3cf157a93ca2bb4e84ad310818c5600508f96718bf1df6e10422f403d395fcc7"
size = 742
path = "tinyrec/img/play.png"

[[payload.files]]
url = "https://raw.githubusercontent.com/tiagolr/tilr_jsfx/9f965d532fb1b55711f98f211fa2a65ed49eea7a/Utility/tinyrec/img/rec_active.png"
sha256 = "c067f6401438ad637a6e7f4dfb56bfcf33c3e8d8b6cefecad53428f31f8df383"
size = 1217
path = "tinyrec/img/rec_active.png"

[[payload.files]]
url = "https://raw.githubusercontent.com/tiagolr/tilr_jsfx/9f965d532fb1b55711f98f211fa2a65ed49eea7a/Utility/tinyrec/img/rec.png"
sha256 = "893fc04fe3f9450be59322c3e2df86b14a63909ee70b3fbdc88b667d068555a5"
size = 1336
path = "tinyrec/img/rec.png"

[[payload.files]]
url = "https://raw.githubusercontent.com/tiagolr/tilr_jsfx/9f965d532fb1b55711f98f211fa2a65ed49eea7a/Utility/tinyrec/img/save.png"
sha256 = "94ae352281fd4e9928ecb1bb122cc273c565913dad06f68f8aef52917863bdef"
size = 594
path = "tinyrec/img/save.png"

[[payload.files]]
url = "https://raw.githubusercontent.com/tiagolr/tilr_jsfx/9f965d532fb1b55711f98f211fa2a65ed49eea7a/Utility/tinyrec/img/stop.png"
sha256 = "939f6c5027088e48e14a3a1ce44e7942b7345bd418fd018309ab5e01fb7ce92e"
size = 555
path = "tinyrec/img/stop.png"

[[payload.files]]
url = "https://raw.githubusercontent.com/tiagolr/tilr_jsfx/9f965d532fb1b55711f98f211fa2a65ed49eea7a/Utility/tinyrec/img/tools.png"
sha256 = "2baea6fa0c0dde4f54f8414b7dce4d4cd524cba16a517925a4414341e26a8496"
size = 742
path = "tinyrec/img/tools.png"

[install]
entry = "tinyrec.jsfx"
