schema = 1
id = "lv2.fatfrog"
name = "FatFrog"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "brummer10"
tags = ["Amplifier"]
description = "A high-gain amplifier model for aggressive guitar tones with saturated sustain and responsive dynamics."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.fatfrog/1.0.0.zip"
sha256 = "26bdbcb6d66d6b50e70844ab3e2c34638caefaef555b012130a17811ffb40176"
size = 817527

[install]
entry = "FatFrog.lv2/manifest.ttl"
