schema = 1
id = "jsfx.tukan.preamp"
name = "PreAmp (Tukan).jsfx"
version = "1.0.0"
format = "jsfx"
arch = ["arm64-v8a"]
manufacturer = "TukanStudios"
tags = ["jsfx"]
description = "PreAmp (Tukan)"
license = "custom"

[payload]
kind = "files"
size = 31724

[[payload.files]]
url = "https://raw.githubusercontent.com/TukanStudios/TUKAN_STUDIOS_PLUGINS/e400035bb4c02bf95c1adbef803cba2e4b6b36b5/PreAmp%20(Tukan)"
sha256 = "96c1ad27c37b5ef2a637509a2ae37a61756eb1483b8a68fdd23d37405da3b0a0"
size = 31724
path = "PreAmp (Tukan).jsfx"

[install]
entry = "PreAmp (Tukan).jsfx"
