schema = 1
id = "lv2.gxhfb"
name = "gx_hfb"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "Guitarix"
tags = ["EQ"]
description = "gx_hfb equalizes the signal to alter its frequency balance and emphasize selected tonal regions."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxhfb/1.0.0.zip"
sha256 = "9abf428b29379a48690cf4e9f279ce219417f5106a8c422c7b0e3aa0a4c4a631"
size = 4152879

[install]
entry = "gx_hfb.lv2/manifest.ttl"
