schema = 1
id = "jsfx.tukan.pads"
name = "Pads (Tukan).jsfx"
version = "1.0.0"
format = "jsfx"
arch = ["arm64-v8a"]
manufacturer = "TukanStudios"
tags = ["jsfx"]
description = "Pads (Tukan)"
license = "custom"

[payload]
kind = "files"
size = 285265

[[payload.files]]
url = "https://raw.githubusercontent.com/TukanStudios/TUKAN_STUDIOS_PLUGINS/e400035bb4c02bf95c1adbef803cba2e4b6b36b5/Pads%20(Tukan)"
sha256 = "8ea164c91f9678548aefd98eee0db0363caf3f8f1ae1961099df257731a84dce"
size = 157072
path = "Pads (Tukan).jsfx"

[[payload.files]]
url = "https://raw.githubusercontent.com/TukanStudios/TUKAN_STUDIOS_PLUGINS/e400035bb4c02bf95c1adbef803cba2e4b6b36b5/SynthAdd/tk_lib.jsfx-inc"
sha256 = "013d71adf0bc9e6adbdfdb1253fd0041e8578af5811506a3b65913384cc59854"
size = 32783
path = "SynthAdd/tk_lib.jsfx-inc"

[[payload.files]]
url = "https://raw.githubusercontent.com/TukanStudios/TUKAN_STUDIOS_PLUGINS/e400035bb4c02bf95c1adbef803cba2e4b6b36b5/SynthAdd/add.gfxlib.jsfx-inc"
sha256 = "79b59b3f9d55012dbc2e7e9f941e4a2f5036c6d18e535aa83714602a3ae1dd04"
size = 5403
path = "SynthAdd/add.gfxlib.jsfx-inc"

[[payload.files]]
url = "https://raw.githubusercontent.com/TukanStudios/TUKAN_STUDIOS_PLUGINS/e400035bb4c02bf95c1adbef803cba2e4b6b36b5/SynthAdd/saikedrums_basic_filters.jsfx-inc"
sha256 = "e86c0202aedc7e6d54395ed607a278629fff2141a0de8058b4b2860033331763"
size = 3554
path = "SynthAdd/saikedrums_basic_filters.jsfx-inc"

[[payload.files]]
url = "https://raw.githubusercontent.com/TukanStudios/TUKAN_STUDIOS_PLUGINS/e400035bb4c02bf95c1adbef803cba2e4b6b36b5/SynthAdd/saikedrums_freq_shift.jsfx-inc"
sha256 = "6efbeab1e896396dc2f26e4cab3be71392c187e9c0e6b0dfff7f39e6192a99bd"
size = 2833
path = "SynthAdd/saikedrums_freq_shift.jsfx-inc"

[[payload.files]]
url = "https://raw.githubusercontent.com/TukanStudios/TUKAN_STUDIOS_PLUGINS/e400035bb4c02bf95c1adbef803cba2e4b6b36b5/SynthAdd/saikedrums_sample_playback.jsfx-inc"
sha256 = "6c9ed409b5be1d03e0566656adc122460e56cdf113c90dc0fbddf5a03e40d37f"
size = 10083
path = "SynthAdd/saikedrums_sample_playback.jsfx-inc"

[[payload.files]]
url = "https://raw.githubusercontent.com/TukanStudios/TUKAN_STUDIOS_PLUGINS/e400035bb4c02bf95c1adbef803cba2e4b6b36b5/SynthAdd/synthdrums.jsfx-inc"
sha256 = "3ea52001b5376be38b153455fbddb9328f8a60109902325c01a8b9933921ffcd"
size = 73537
path = "SynthAdd/synthdrums.jsfx-inc"

[install]
entry = "Pads (Tukan).jsfx"
