schema = 1
id = "jsfx.reaper.midi-velocifier-ii"
source = "https://www.reaper.fm/"
name = "MIDI Velocity Variation Generator"
version = "1.0.0"
format = "jsfx"
arch = ["arm64-v8a"]
manufacturer = "IXix"
tags = ["jsfx","MIDI","processing","mapping"]
description = "A MIDI utility varies note velocities to add humanized dynamics and movement to otherwise uniform performances."
license = "GPL-3.0-or-later"

[payload]
kind = "file"
url = "../../payload/jsfx.reaper.midi-velocifier-ii/MIDI_Velocifier II.jsfx"
sha256 = "ad7f13fdc73f9e54111bf0f615f399098789462d461cc13803e08289730fc95e"
size = 4900

[install]
entry = "MIDI_Velocifier II.jsfx"
