schema = 1
id = "jsfx.tilr.gate1"
name = "gate1.jsfx"
version = "1.1.5"
format = "jsfx"
arch = ["arm64-v8a"]
manufacturer = "tilr"
tags = ["jsfx"]
description = "GATE-1"
license = "custom"

[payload]
kind = "files"
size = 841667

[[payload.files]]
url = "https://raw.githubusercontent.com/tiagolr/tilr_jsfx/8379da177843b130bcd828cb9a0bb87ce8a508e0/Modulation/gate1.jsfx"
sha256 = "a7df9523d3042693b8d7edaf31d5b03818471b038ce7e4059232fc1fc9f79504"
size = 24162
path = "gate1.jsfx"

[[payload.files]]
url = "https://raw.githubusercontent.com/tiagolr/tilr_jsfx/8379da177843b130bcd828cb9a0bb87ce8a508e0/Modulation/gate1.jsfx.RPL"
sha256 = "abb9d3e7499ff495c6390ffaeedb078d1e321bace4eaede43811506f35fe177a"
size = 799808
path = "gate1.jsfx.RPL"

[[payload.files]]
url = "https://raw.githubusercontent.com/tiagolr/tilr_jsfx/8379da177843b130bcd828cb9a0bb87ce8a508e0/Modulation/gate1/gate.array.jsfx-inc"
sha256 = "4ade80a551384328629078a8caf18b21e732b0d7f464e86363d3ffe1656d9d20"
size = 6004
path = "gate1/gate.array.jsfx-inc"

[[payload.files]]
url = "https://raw.githubusercontent.com/tiagolr/tilr_jsfx/8379da177843b130bcd828cb9a0bb87ce8a508e0/Modulation/gate1/gate.curvelib.jsfx-inc"
sha256 = "981a2f341cb2c6f6a93e89f2de83b9f9f885155d50cceae7f93563787d267528"
size = 10680
path = "gate1/gate.curvelib.jsfx-inc"

[[payload.files]]
url = "https://raw.githubusercontent.com/tiagolr/tilr_jsfx/8379da177843b130bcd828cb9a0bb87ce8a508e0/Modulation/gate1/gate.mouselib.jsfx-inc"
sha256 = "9aac751ec32b12d2172c0eae06ad27ce582b18c663c91958cf17008f1106062e"
size = 1013
path = "gate1/gate.mouselib.jsfx-inc"

[install]
entry = "gate1.jsfx"
