schema = 1
id = "lv2.gxbooster"
name = "gxbooster"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "Guitarix"
tags = ["Utility"]
description = "A two-band boost processor for independently emphasizing low and high frequencies in an instrument signal."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxbooster/1.0.0.zip"
sha256 = "dca2d49d8809376f7f6edd2f92f9e2b13dd678716624fd3927f1b7e18ef30ae8"
size = 4399870

[install]
entry = "gxbooster.lv2/manifest.ttl"
