schema = 1
id = "jsfx.tukan.tool"
name = "Tool (Tukan).jsfx"
version = "1.0.0"
format = "jsfx"
arch = ["arm64-v8a"]
manufacturer = "TukanStudios"
tags = ["jsfx"]
description = "Tool (Tukan)"
license = "custom"

[payload]
kind = "files"
size = 36695

[[payload.files]]
url = "https://raw.githubusercontent.com/TukanStudios/TUKAN_STUDIOS_PLUGINS/e400035bb4c02bf95c1adbef803cba2e4b6b36b5/Tool%20(Tukan)"
sha256 = "d003f4288c203640341a469bf8bff6d23fa088de5c892242bf44507de4ca78bd"
size = 36695
path = "Tool (Tukan).jsfx"

[install]
entry = "Tool (Tukan).jsfx"
