schema = 1
id = "lv2.gxredeye"
name = "gx_redeye"
version = "1.0.0"
format = "lv2"
arch = ["arm64-v8a"]
manufacturer = "Guitarix"
tags = ["Amplifier"]
description = "Amplifier simulation."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxredeye/1.0.0.zip"
sha256 = "1fda4f3b59688e4f12f96f33dcb742cac9988d4e4396edcd3bf6c7e14dc45c40"
size = 6879103

[install]
entry = "gx_redeye.lv2/manifest.ttl"
