schema = 1
id = "lv2.xdarkterror"
name = "XDarkTerror"
version = "1.0.0"
format = "lv2"
source = "https://github.com/brummer10/XDarkTerror.lv2"
arch = ["arm64-v8a"]
manufacturer = "brummer10"
tags = ["Amplifier","Distortion"]
description = "XDarkTerror simulates a valve guitar amplifier for dark, driven tone and harmonic coloration."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.xdarkterror/1.0.0.zip"
sha256 = "293ce74d5a661d83c66714e28bdc260bd6435377900fc42e8e4c8e595d0810a7"
size = 851311

[install]
entry = "XDarkTerror.lv2/manifest.ttl"
