schema = 1
id = "jsfx.tukan.exciter-with-fat-bottom-s2"
name = "Exciter with fat bottom S2 (Tukan).jsfx"
version = "1.0.0"
format = "jsfx"
arch = ["arm64-v8a"]
manufacturer = "TukanStudios"
tags = ["jsfx"]
description = "Exciter with fat bottom S2 (Tukan)"
license = "custom"

[payload]
kind = "files"
size = 103756

[[payload.files]]
url = "https://raw.githubusercontent.com/TukanStudios/TUKAN_STUDIOS_PLUGINS/e400035bb4c02bf95c1adbef803cba2e4b6b36b5/Exciter%20with%20fat%20bottom%20S2%20(Tukan)"
sha256 = "8202b77fba920cea53130a5e2845626e40c6ceb4d70cc9c0cd39c29bd579bf92"
size = 70580
path = "Exciter with fat bottom S2 (Tukan).jsfx"

[[payload.files]]
url = "https://raw.githubusercontent.com/TukanStudios/TUKAN_STUDIOS_PLUGINS/e400035bb4c02bf95c1adbef803cba2e4b6b36b5/S2GFX/tk_lib.jsfx-inc"
sha256 = "9033bfcdf5e60a8805484837faa0138519ae14e1f29a3c773993f6209bc49754"
size = 33176
path = "S2GFX/tk_lib.jsfx-inc"

[install]
entry = "Exciter with fat bottom S2 (Tukan).jsfx"
