schema = 1
id = "jsfx.geraint.spectrum-matcher"
name = "Spectrum Matcher.jsfx"
version = "1.7.1"
format = "jsfx"
arch = ["arm64-v8a"]
manufacturer = "Geraint Luff"
tags = ["jsfx"]
description = "Spectrum Matcher (by Geraint Luff)"
license = "custom"

[payload]
kind = "files"
size = 222198

[[payload.files]]
url = "https://raw.githubusercontent.com/geraintluff/jsfx/e98d64401ba57590b7ea0d3592675accb43667da/releases/Spectrum-Matcher/1.7.1/Spectrum-Matcher/Spectrum%20Matcher.jsfx"
sha256 = "2b207b9c1664573c0ac3c170d8dd83b00a7c90e7da9136f9596d520240e6dc97"
size = 128594
path = "Spectrum Matcher.jsfx"

[[payload.files]]
url = "https://raw.githubusercontent.com/geraintluff/jsfx/e98d64401ba57590b7ea0d3592675accb43667da/releases/Spectrum-Matcher/1.7.1/Spectrum-Matcher/ui-lib.jsfx-inc"
sha256 = "a23465e15361743e7d404af8e0fac7ecedfa5dc615b2825acf0b7eee9361d3a7"
size = 93604
path = "ui-lib.jsfx-inc"

[install]
entry = "Spectrum Matcher.jsfx"
