schema = 1
id = "lv2.gxhyperion"
name = "GxHyperion"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "GxPlugins"
tags = ["Distortion"]
description = "Simulation of the Hyperion Fuzz Pedal."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxhyperion/1.0.0.zip"
sha256 = "56e8221a6773e3f9d650290b4aed324639dcaee7aa378670caa967b71612cd09"
size = 1374977

[install]
entry = "GxHyperion.lv2/manifest.ttl"
