schema = 1
id = "lv2.gxguvnor"
name = "GxGuvnor"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "GxPlugins"
tags = ["Distortion"]
description = "Overdrive/distortion pedal simulation."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxguvnor/1.0.0.zip"
sha256 = "7444c15067ad0fff213fc05fbbdd414812a2af33fd043b09d6d78ea9957247fe"
size = 2192293

[install]
entry = "GxGuvnor.lv2/manifest.ttl"
