schema = 1
id = "lv2.gxguvnor"
name = "GxGuvnor"
version = "1.0.0"
format = "lv2"
arch = ["arm64-v8a"]
manufacturer = "GxPlugins"
tags = ["Distortion"]
description = "Overdrive/distortion pedal simulation."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxguvnor/1.0.0.zip"
sha256 = "f5167a7856a1e497ff13178bc24e2a4f246a9e09072f5478974e061bd7e01a47"
size = 2192290

[install]
entry = "GxGuvnor.lv2/manifest.ttl"
