schema = 1
id = "lv2.gxquack"
name = "GxQuack"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "GxPlugins"
tags = ["Envelope"]
description = "envelope controlled wah pedal with some extra features."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxquack/1.0.0.zip"
sha256 = "598ceebc756e9db8641aebd20e2c7ea54ba7245fd32984510951c588546ed03e"
size = 1378715

[install]
entry = "GxQuack.lv2/manifest.ttl"
