schema = 1
id = "lv2.gxmbcompressor"
name = "gx_mbcompressor"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "Guitarix"
tags = ["Compressor","Dynamics"]
description = "gx_mbcompressor controls dynamics independently across multiple frequency bands for more focused compression."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxmbcompressor/1.0.0.zip"
sha256 = "e5e0a7c5d33d718046eb1566ce647cb0a09c23a9e55cd0de5933ed12ed490234"
size = 5054075

[install]
entry = "gx_mbcompressor.lv2/manifest.ttl"
