schema = 1
id = "lv2.gxmbcompressor"
name = "gx_mbcompressor"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "Guitarix"
tags = ["Compressor","Dynamics"]
description = "gx_mbcompressor controls dynamics independently across multiple frequency bands for more focused compression."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxmbcompressor/1.0.0.zip"
sha256 = "f0e13ead8b51c91ea5a873323b124fb842077fbf92787fbdf98047a75c4dd6f2"
size = 5054073

[install]
entry = "gx_mbcompressor.lv2/manifest.ttl"
