schema = 1
id = "lv2.gxtubedistortion"
name = "GxTubeDistortion"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "GxPlugins"
tags = ["Distortion"]
description = "Simulation of a Tube based Distortion Pedal."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxtubedistortion/1.0.0.zip"
sha256 = "b8227d22a99ef0f41724c8097f55bc5a18e6322b4461727ac733681251d1c382"
size = 1210382

[install]
entry = "GxTubeDistortion.lv2/manifest.ttl"
