schema = 1
id = "jsfx.tilr.quickdualdelay"
name = "QuickDualDelay"
version = "1.0"
format = "jsfx"
arch = ["arm64-v8a"]
manufacturer = "tilr"
tags = ["jsfx", "delay", "stereo"]
source = "https://github.com/tiagolr/tilr_jsfx"
description = "A dual delay effect for creating independent left and right echoes with stereo width."
license = "custom"

[payload]
kind = "files"
size = 42046

[[payload.files]]
url = "https://raw.githubusercontent.com/tiagolr/tilr_jsfx/9ee52fd4bfd73f693acac2e35e30dd277fd88ea3/Delay/QuickDualDelay.jsfx"
sha256 = "b3b59fca58f8140815f11e557a39b404b624038d01f085d7a35653d43e741724"
size = 5273
path = "QuickDualDelay.jsfx"

[[payload.files]]
url = "https://raw.githubusercontent.com/tiagolr/tilr_jsfx/9ee52fd4bfd73f693acac2e35e30dd277fd88ea3/Delay/qddelay/qdd.delay.jsfx-inc"
sha256 = "ce3326988143007f20dd495145e4fe073dfcf92aa8dd5fd7ab74b9f80219100e"
size = 17528
path = "qddelay/qdd.delay.jsfx-inc"

[[payload.files]]
url = "https://raw.githubusercontent.com/tiagolr/tilr_jsfx/9ee52fd4bfd73f693acac2e35e30dd277fd88ea3/Delay/qddelay/qdd.rbj_filter.jsfx-inc"
sha256 = "7a5885bb0c1523856ac682a9fc9a499c3a9de12d7b87837664f9e4ffefbc341b"
size = 9422
path = "qddelay/qdd.rbj_filter.jsfx-inc"

[[payload.files]]
url = "https://raw.githubusercontent.com/tiagolr/tilr_jsfx/9ee52fd4bfd73f693acac2e35e30dd277fd88ea3/Delay/qddelay/qdd.saike_pitchlib.jsfx-inc"
sha256 = "07dd4fbdc5b276237aed10b3f5c3bb1ae97e7894f56826280f593dc2c489524b"
size = 9823
path = "qddelay/qdd.saike_pitchlib.jsfx-inc"

[install]
entry = "QuickDualDelay.jsfx"
