schema = 1
id = "jsfx.joep.saike-morph"
name = "Saike_Morph"
version = "0.18"
format = "jsfx"
arch = ["arm64-v8a"]
manufacturer = "Joep Vanlier"
source = "https://github.com/JoepVanlier/JSFX"
tags = ["Filter","Modulation"]
description = "Saike_Morph morphs between filtering responses to create continuously changing spectral shapes."
license = "custom"

[payload]
kind = "files"
size = 33650

[[payload.files]]
url = "https://raw.githubusercontent.com/JoepVanlier/JSFX/5cf8ec39ef56c9a1960d2b802be33c13d74bf228/Basics/Saike_Morph.jsfx"
sha256 = "1bf59410f4b2dab4933fadef0f9bbea4bfd94a276823f4d20c018a9abbac0f29"
size = 33650
path = "Saike_Morph.jsfx"

[install]
entry = "Saike_Morph.jsfx"
