schema = 1
id = "jsfx.reaper.statevariable"
name = "State Variable Morphing Filter"
version = "1.0.0"
format = "jsfx"
arch = ["arm64-v8a"]
manufacturer = "Liteon"
tags = ["jsfx","filter","multimode"]
description = "State Variable Morphing Filter"
license = "GPL"

[payload]
kind = "file"
url = "../../payload/jsfx.reaper.statevariable/statevariable.jsfx"
sha256 = "ef24a9104d74826e8af4e954ff81563a15d7bd602ab7527f8082129d612d5c8f"
size = 12499

[install]
entry = "statevariable.jsfx"
