schema = 1
id = "lv2.gxmicroamp"
name = "GxMicroAmp"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "GxPlugins"
tags = ["Amplifier"]
description = "The MicroAmp is designed to be a transparent clean volume booster."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxmicroamp/1.0.0.zip"
sha256 = "e1d56df70fd8ec75150e73465e3f3d9ca91233068908d635b9779ee472918232"
size = 1091724

[install]
entry = "GxMicroAmp.lv2/manifest.ttl"
