schema = 1
id = "lv2.gxmicroamp"
name = "GxMicroAmp"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "GxPlugins"
tags = ["Amplifier"]
description = "The MicroAmp is designed to be a transparent clean volume booster."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxmicroamp/1.0.0.zip"
sha256 = "ca10487a1a49dbb52fe7293137c4206b9f06851fec661788cc6c1f5bfc594090"
size = 1091724

[install]
entry = "GxMicroAmp.lv2/manifest.ttl"
