schema = 1
id = "lv2.gxcabsim"
name = "GxCabSim"
version = "1.0.0"
format = "lv2"
source = "https://github.com/brummer10/GxCabSim.lv2"
arch = ["arm64-v8a"]
manufacturer = "brummer10"
tags = ["Filter"]
description = "A cabinet simulation processor for shaping instrument tone with controllable dynamics and harmonic color."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxcabsim/1.0.0.zip"
sha256 = "42cb07f108166648b80cea3d1667056df79503333a6888910d5d9f5a2b820d80"
size = 1037071

[install]
entry = "GxCabSim.lv2/manifest.ttl"
