schema = 1
id = "lv2.aidadsp"
name = "aidadsp"
version = "1.0.0"
format = "lv2"
source = "https://github.com/AidaDSP/aidadsp-lv2"
arch = ["arm64-v8a"]
manufacturer = "Aida DSP"
tags = ["Simulator"]
description = "AIDA-X is an Amp Model Player, allowing it to load models of AI trained music gear, which you can then play through!"
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.aidadsp/1.0.0.zip"
sha256 = "c1699c5327c2c9038f1da1cb215c4d0e00f8f0efeff898c59e6bbe1c1dbf4489"
size = 1913154

[install]
entry = "aidadsp.lv2/manifest.ttl"
