schema = 1
id = "jsfx.jozmac.jm-gen-tetrad-spiral-farey"
name = "JM_gen_Tetrad_Spiral_Farey"
version = "1.0"
format = "jsfx"
arch = ["arm64-v8a"]
manufacturer = "Jozef Mackowiak"
source = "https://github.com/jozmac/reapack-jm"
tags = ["Synth","Pitch"]
description = "A generator for four-note pitch structures organized using spiral and Farey-sequence relationships."
license = "custom"

[payload]
kind = "files"
size = 55333

[[payload.files]]
url = "https://raw.githubusercontent.com/jozmac/reapack-jm/4f507485554c90dcb6a3670058a8f4812c851518/Effects/JM_gen_Tetrad_Spiral_Farey.jsfx"
sha256 = "6cc2c5f41603ae7d33d547f0375af40f35e3aef829c10e1229e277c275e28d49"
size = 28391
path = "JM_gen_Tetrad_Spiral_Farey.jsfx"

[[payload.files]]
url = "https://raw.githubusercontent.com/jozmac/reapack-jm/4f507485554c90dcb6a3670058a8f4812c851518/ThirdParty/Tale/poly_blep.jsfx-inc"
sha256 = "0f2dc90d0d8110fc37ba788ca4da43cb5564880dc5b18cd6ed4e45a67e03d40f"
size = 26942
path = "Tale/poly_blep.jsfx-inc"

[install]
entry = "JM_gen_Tetrad_Spiral_Farey.jsfx"
