schema = 1
id = "lv2.collisiondrive"
name = "CollisionDrive"
version = "1.0.0"
format = "lv2"
source = "https://github.com/brummer10/CollisionDrive"
arch = ["arm64-v8a"]
manufacturer = "brummer10"
tags = ["Distortion"]
description = "A drive processor for punchy clipped guitar tones with controllable gain and tonal shaping."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.collisiondrive/1.0.0.zip"
sha256 = "005bedf23ccf298d0f437a19774cbfc38e17d22934476f41fe4654549875e85e"
size = 2459043

[install]
entry = "CollisionDrive.lv2/manifest.ttl"
