schema = 1
id = "jsfx.joep.saike-final-boss"
name = "saike_final_boss"
version = "0.13"
format = "jsfx"
arch = ["arm64-v8a"]
manufacturer = "Joep Vanlier"
source = "https://github.com/JoepVanlier/JSFX"
tags = ["Dynamics","Compressor"]
description = "saike_final_boss controls peaks and overall dynamics as a final-stage processor for mix-bus level management."
license = "custom"

[payload]
kind = "files"
size = 754254

[[payload.files]]
url = "https://raw.githubusercontent.com/JoepVanlier/JSFX/9a94fda395cc6252cfc5f86010b65bc07b27dcea/FinalBoss/saike_final_boss.jsfx"
sha256 = "b526ed60e4392a117dde8c01e5bc71c4e4f1a7722c0b29772e6ca2879c623f9a"
size = 34757
path = "saike_final_boss.jsfx"

[[payload.files]]
url = "https://raw.githubusercontent.com/JoepVanlier/JSFX/9a94fda395cc6252cfc5f86010b65bc07b27dcea/FinalBoss/saike_allpass_dependencies/font.png"
sha256 = "872a066383d4a7d5b73b4bc03e572f6d6fd4f4717a55da79a640f853de2d493d"
size = 416
path = "saike_allpass_dependencies/font.png"

[[payload.files]]
url = "https://raw.githubusercontent.com/JoepVanlier/JSFX/9a94fda395cc6252cfc5f86010b65bc07b27dcea/FinalBoss/saike_allpass_dependencies/hell_glow2.png"
sha256 = "cb8306b4292ba5c24624067a139bb010fe1620a7cf9e516a08921b788341cd0a"
size = 284591
path = "saike_allpass_dependencies/hell_glow2.png"

[[payload.files]]
url = "https://raw.githubusercontent.com/JoepVanlier/JSFX/9a94fda395cc6252cfc5f86010b65bc07b27dcea/FinalBoss/saike_allpass_dependencies/hori.png"
sha256 = "59d5ca5bd49dab3786b4226125b3a111aa566819d9cfb4cfcd9833fc595da16a"
size = 35046
path = "saike_allpass_dependencies/hori.png"

[[payload.files]]
url = "https://raw.githubusercontent.com/JoepVanlier/JSFX/9a94fda395cc6252cfc5f86010b65bc07b27dcea/FinalBoss/saike_allpass_dependencies/saike_allpass_pitchlib.jsfx-inc"
sha256 = "73623dbd9cca74302d340943a610dfed63a64b24293b2d31be70c1dead91cf3a"
size = 10405
path = "saike_allpass_dependencies/saike_allpass_pitchlib.jsfx-inc"

[[payload.files]]
url = "https://raw.githubusercontent.com/JoepVanlier/JSFX/9a94fda395cc6252cfc5f86010b65bc07b27dcea/FinalBoss/saike_allpass_dependencies/saike_allpass_pixel_gfx.jsfx-inc"
sha256 = "5cc37ee22eee3ba668d44d49cd6954ed577ef110f054cc2e722138a401ef27ad"
size = 28249
path = "saike_allpass_dependencies/saike_allpass_pixel_gfx.jsfx-inc"

[[payload.files]]
url = "https://raw.githubusercontent.com/JoepVanlier/JSFX/9a94fda395cc6252cfc5f86010b65bc07b27dcea/FinalBoss/saike_allpass_dependencies/saike_allpass_toy_cabs.jsfx-inc"
sha256 = "78b35fd9c3d7a121954b3a56b64ea0d7878a0df29de58e71853bc8e92b607de4"
size = 21622
path = "saike_allpass_dependencies/saike_allpass_toy_cabs.jsfx-inc"

[[payload.files]]
url = "https://raw.githubusercontent.com/JoepVanlier/JSFX/9a94fda395cc6252cfc5f86010b65bc07b27dcea/FinalBoss/saike_allpass_dependencies/saike_allpass_toy_fx.jsfx-inc"
sha256 = "fe438d7e2046b75e56204e8c6525c5ece9fe1c6fab7fde478fe26df1fd7910bb"
size = 44973
path = "saike_allpass_dependencies/saike_allpass_toy_fx.jsfx-inc"

[[payload.files]]
url = "https://raw.githubusercontent.com/JoepVanlier/JSFX/9a94fda395cc6252cfc5f86010b65bc07b27dcea/FinalBoss/saike_allpass_dependencies/skull_x+.png"
sha256 = "f2de68533fffab5a0fcaff85ba1c6cfe77ee90e42a8fb515290c621694a941ca"
size = 20467
path = "saike_allpass_dependencies/skull_x+.png"

[[payload.files]]
url = "https://raw.githubusercontent.com/JoepVanlier/JSFX/9a94fda395cc6252cfc5f86010b65bc07b27dcea/FinalBoss/saike_allpass_dependencies/skull_x-.png"
sha256 = "7e08be94a466eafa66e80767cadb86b490fab53090854b5acb2d0aa41ede8797"
size = 20351
path = "saike_allpass_dependencies/skull_x-.png"

[[payload.files]]
url = "https://raw.githubusercontent.com/JoepVanlier/JSFX/9a94fda395cc6252cfc5f86010b65bc07b27dcea/FinalBoss/saike_allpass_dependencies/skull_y+.png"
sha256 = "842d59b22d6124be2b3d55ca17243ea9835afbe256f64b6ccdfa69be92579acf"
size = 19162
path = "saike_allpass_dependencies/skull_y+.png"

[[payload.files]]
url = "https://raw.githubusercontent.com/JoepVanlier/JSFX/9a94fda395cc6252cfc5f86010b65bc07b27dcea/FinalBoss/saike_allpass_dependencies/skull_y-.png"
sha256 = "3840e447bf8eca967dd3acb72ae0a9136cfc635051de5da316e37e8ca67b134f"
size = 18035
path = "saike_allpass_dependencies/skull_y-.png"

[[payload.files]]
url = "https://raw.githubusercontent.com/JoepVanlier/JSFX/9a94fda395cc6252cfc5f86010b65bc07b27dcea/FinalBoss/saike_allpass_dependencies/skullface_edges.png"
sha256 = "931aa023138e1db8d97ff160f3a20741ec9e01f04a33ca284cd632fb08c49da9"
size = 35204
path = "saike_allpass_dependencies/skullface_edges.png"

[[payload.files]]
url = "https://raw.githubusercontent.com/JoepVanlier/JSFX/9a94fda395cc6252cfc5f86010b65bc07b27dcea/FinalBoss/saike_allpass_dependencies/skullface_edges3.png"
sha256 = "1593bce45090a1fca5e75458e10b9077bc14da733bd81ea1eff0a10e45277a34"
size = 27982
path = "saike_allpass_dependencies/skullface_edges3.png"

[[payload.files]]
url = "https://raw.githubusercontent.com/JoepVanlier/JSFX/9a94fda395cc6252cfc5f86010b65bc07b27dcea/FinalBoss/saike_allpass_dependencies/skullface_hl.png"
sha256 = "adbfefe9d94e97612836a98fa9f9c6e52fcda3f6ab66bdc4957f31d2022c86f8"
size = 3930
path = "saike_allpass_dependencies/skullface_hl.png"

[[payload.files]]
url = "https://raw.githubusercontent.com/JoepVanlier/JSFX/9a94fda395cc6252cfc5f86010b65bc07b27dcea/FinalBoss/saike_allpass_dependencies/skullface_monochrome.png"
sha256 = "59c7d5ecad22961179f8028fb3137393285f7e06f39e715f79079b0a9ca36a4d"
size = 24410
path = "saike_allpass_dependencies/skullface_monochrome.png"

[[payload.files]]
url = "https://raw.githubusercontent.com/JoepVanlier/JSFX/9a94fda395cc6252cfc5f86010b65bc07b27dcea/FinalBoss/saike_allpass_dependencies/x_kernel.png"
sha256 = "c2a6fa49265a2bd1010b724b49ea514af30b6c9a6d9d31d05ca27a63f1646ad3"
size = 55496
path = "saike_allpass_dependencies/x_kernel.png"

[[payload.files]]
url = "https://raw.githubusercontent.com/JoepVanlier/JSFX/9a94fda395cc6252cfc5f86010b65bc07b27dcea/FinalBoss/saike_allpass_dependencies/y_kernel.png"
sha256 = "6246017b8ae47e10346c1599e6182aa7e5ebcb1f006e84bcf58e64ec177997e0"
size = 59250
path = "saike_allpass_dependencies/y_kernel.png"

[[payload.files]]
url = "https://raw.githubusercontent.com/JoepVanlier/JSFX/9a94fda395cc6252cfc5f86010b65bc07b27dcea/FinalBoss/saike_final_boss.jsfx.rpl"
sha256 = "1e20fb5ee68ac993cd2e2d4f129f21b0562ca58e27d818d698dc8799abe04b63"
size = 9908
path = "saike_final_boss.jsfx.rpl"

[install]
entry = "saike_final_boss.jsfx"
