schema = 1
id = "jsfx.jclones.jclones-satbuss"
name = "JClones_SatBuss.jsfx"
version = "1.1.0"
format = "jsfx"
arch = ["arm64-v8a"]
manufacturer = "JClones"
tags = ["jsfx"]
description = "JClones_SatBuss"
license = "custom"

[payload]
kind = "files"
size = 8260

[[payload.files]]
url = "https://raw.githubusercontent.com/JClones/JSFXClones/9486f9cb9bc7b929d8e5db2959db0b97326d1a18/jsfx/JClones_SatBuss.jsfx"
sha256 = "183594fb7c5ac4f5c9568f9009026e923bfcb064fa9bc0e5f0aab5ca09050151"
size = 8260
path = "JClones_SatBuss.jsfx"

[install]
entry = "JClones_SatBuss.jsfx"
