schema = 1
id = "jsfx.joep.nott"
name = "nott.jsfx"
version = "0.16"
format = "jsfx"
arch = ["arm64-v8a"]
manufacturer = "Joep Vanlier"
tags = ["jsfx"]
description = "Saike Not OTT (ALPHA)"
license = "custom"

[payload]
kind = "files"
size = 121786

[[payload.files]]
url = "https://raw.githubusercontent.com/JoepVanlier/JSFX/e17c5dbfe80912db390b25de69b4579d2beee058/NOTT/nott.jsfx"
sha256 = "c588bfdae95df7482fdf55222e3b1d07a5a8b96d7cacbaf87e9447a273caec4a"
size = 121786
path = "nott.jsfx"

[install]
entry = "nott.jsfx"
