schema = 1
id = "lv2.gxbmp"
name = "gx_bmp"
version = "1.0.0"
format = "lv2"
arch = ["arm64-v8a"]
manufacturer = "Guitarix"
tags = ["Distortion"]
description = "Distortion/overdrive effect."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxbmp/1.0.0.zip"
sha256 = "bde581bdc459fcb18279aa4b2b3217304e4b9f4e5031222acf41f54f7df4a99d"
size = 3482129

[install]
entry = "gx_bmp.lv2/manifest.ttl"
