schema = 1
id = "lv2.gxbmp"
name = "gx_bmp"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "Guitarix"
tags = ["Distortion","Saturation"]
description = "gx_bmp is a pedal-style distortion effect that adds sustained clipping and thick harmonic coloration."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxbmp/1.0.0.zip"
sha256 = "fc8af20542223c67360ea919c7e70f16d9717faadd169dafa259ad5fabe1cfd6"
size = 3482128

[install]
entry = "gx_bmp.lv2/manifest.ttl"
