schema = 1
id = "lv2.gxaclipper"
name = "gx_aclipper"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "Guitarix"
tags = ["Distortion","Dynamics"]
description = "gx_aclipper clips signal peaks to create audible distortion and denser harmonic content."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxaclipper/1.0.0.zip"
sha256 = "72ac40bd8d1c175f7fd62eafccb9c3851b79a9fdbfd41addf165e9ff812f371a"
size = 3483976

[install]
entry = "gx_aclipper.lv2/manifest.ttl"
