schema = 1
id = "lv2.gxgcb95"
name = "gx_gcb_95"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "Guitarix"
tags = ["Filter","Modulation"]
description = "gx_gcb_95 produces wah-pedal effects by moving a resonant filter through the instrument spectrum."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxgcb95/1.0.0.zip"
sha256 = "b52aef9681216e9f5f7a7f4af32fd8a46e0c83a821a3a959b03774509fb1e64d"
size = 3473095

[install]
entry = "gx_gcb_95.lv2/manifest.ttl"
