schema = 1
id = "lv2.gxgcb95"
name = "gx_gcb_95"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "Guitarix"
tags = ["Filter","Modulation"]
description = "gx_gcb_95 produces wah-pedal effects by moving a resonant filter through the instrument spectrum."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxgcb95/1.0.0.zip"
sha256 = "4a5607619dbc47c688235a693a6efd0ab540fd603834ba1c091c3b054f85a25d"
size = 3473095

[install]
entry = "gx_gcb_95.lv2/manifest.ttl"
