schema = 1
id = "lv2.gxhotbox"
name = "GxHotBox"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "GxPlugins"
tags = ["Distortion"]
description = "Analouge simulation of a tube preamp with overdrive and interactive tone control."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxhotbox/1.0.0.zip"
sha256 = "584d46fcb08ffd9d218b03210816fc1ac61c0fc789d45e6a718808e216a6daa3"
size = 1632060

[install]
entry = "GxHotBox.lv2/manifest.ttl"
