schema = 1
id = "lv2.gxhotbox"
name = "GxHotBox"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "GxPlugins"
tags = ["Distortion"]
description = "Analouge simulation of a tube preamp with overdrive and interactive tone control."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxhotbox/1.0.0.zip"
sha256 = "0c73703de541cd7ffb3517f22bf4bffcfa6e2a02a460a47a22578b1508ba341f"
size = 1632062

[install]
entry = "GxHotBox.lv2/manifest.ttl"
