schema = 1
id = "lv2.gxsunface"
name = "GxSunFace"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "GxPlugins"
tags = ["Distortion"]
description = "A classic fuzz face with some light modifications."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxsunface/1.0.0.zip"
sha256 = "f6f052c8269adcbf7fad8f6c52c3bc9a4374a47cd5c5529fee0b99c07a1351d0"
size = 1715684

[install]
entry = "GxSunFace.lv2/manifest.ttl"
