schema = 1
id = "lv2.gxfz1b"
name = "GxFz1b"
version = "1.0.0"
format = "lv2"
arch = ["arm64-v8a"]
manufacturer = "GxPlugins"
tags = ["Distortion"]
description = "Vintage Fuzz Pedal simulation."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxfz1b/1.0.0.zip"
sha256 = "49d61694a6af712a1f091eb19849deaec3e5adf9be128ec052cde13e8e571087"
size = 1470788

[install]
entry = "GxFz1b.lv2/manifest.ttl"
