schema = 1
id = "lv2.gxfz1b"
name = "GxFz1b"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "GxPlugins"
tags = ["Distortion"]
description = "GxFz1b simulates a vintage fuzz pedal, producing heavily clipped, harmonically rich guitar tones."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxfz1b/1.0.0.zip"
sha256 = "5c3fea2f8997ace66b9945a8584343cf3388f6a2e80326e9ac54cc48c15c60cf"
size = 1470785

[install]
entry = "GxFz1b.lv2/manifest.ttl"
