schema = 1
id = "jsfx.joep.satanverb"
name = "SatanVerb.jsfx"
version = "0.12"
format = "jsfx"
arch = ["arm64-v8a"]
manufacturer = "Joep Vanlier"
tags = ["jsfx"]
description = "Satan verb (Saike)"
license = "custom"

[payload]
kind = "files"
size = 85163

[[payload.files]]
url = "https://raw.githubusercontent.com/JoepVanlier/JSFX/34d6b72aa6784b40a10342ca69bbef518ca0f566/SatanVerb/SatanVerb.jsfx"
sha256 = "c7dd2ac0882b391c915fc98d0b1f124e2f1d1963372e3539e78bbf0672babecd"
size = 30186
path = "SatanVerb.jsfx"

[[payload.files]]
url = "https://raw.githubusercontent.com/JoepVanlier/JSFX/34d6b72aa6784b40a10342ca69bbef518ca0f566/SatanVerb/SatanVerb_Dependencies/widgetdata_satan.jsfx-inc"
sha256 = "0ebedd23102e3b72e3a8f3cbebc4a04a7df0b9d32a992440117068519bef03cd"
size = 5635
path = "SatanVerb_Dependencies/widgetdata_satan.jsfx-inc"

[[payload.files]]
url = "https://raw.githubusercontent.com/JoepVanlier/JSFX/34d6b72aa6784b40a10342ca69bbef518ca0f566/SatanVerb/SatanVerb_Dependencies/widgets_satan.jsfx-inc"
sha256 = "c68eb750eea127cd3bc54d4e6463df357fecc31ae1fb3c1f5a1b97e2532afa34"
size = 44479
path = "SatanVerb_Dependencies/widgets_satan.jsfx-inc"

[[payload.files]]
url = "https://raw.githubusercontent.com/JoepVanlier/JSFX/34d6b72aa6784b40a10342ca69bbef518ca0f566/SatanVerb/SatanVerb.jsfx.rpl"
sha256 = "987b06468a8161f05633cfba3238b5191fc35619881ea355dd38751caf3f3c98"
size = 4863
path = "SatanVerb.jsfx.rpl"

[install]
entry = "SatanVerb.jsfx"
