schema = 1
id = "lv2.gxliquiddrive"
name = "GxLiquidDrive"
version = "1.0.0"
format = "lv2"
arch = ["arm64-v8a"]
manufacturer = "GxPlugins"
tags = ["Distortion"]
description = "Warm, responsive overdrive ranging from mild blues grit to aggressive rock drive."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxliquiddrive/1.0.0.zip"
sha256 = "94b14af9d60e39000aba7dd94c486434e9f848f03a6eb1548922930332dbd3d3"
size = 1518514

[install]
entry = "GxLiquidDrive.lv2/manifest.ttl"
