schema = 1
id = "lv2.gxduckdelayst"
name = "gx_duck_delay_st"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "Guitarix"
tags = ["Delay"]
description = "Stereo envelope-controlled ducking delay."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxduckdelayst/1.0.0.zip"
sha256 = "eda0eba3c9b483874ddfe2756a32e26c9bb25d7c2d600e55ac38803f3bb35dc2"
size = 4259637

[install]
entry = "gx_duck_delay_st.lv2/manifest.ttl"
