schema = 1
id = "jsfx.jozmac.jm-ana-vectorscope"
name = "JM_ana_Vectorscope"
version = "1.0"
format = "jsfx"
arch = ["arm64-v8a"]
manufacturer = "Jozef Mackowiak"
source = "https://github.com/jozmac/reapack-jm"
tags = ["Analyzer","Stereo"]
description = "JM_ana_Vectorscope plots left-right signal relationships to evaluate stereo width and phase."
license = "custom"

[payload]
kind = "files"
size = 60417

[[payload.files]]
url = "https://raw.githubusercontent.com/jozmac/reapack-jm/4f507485554c90dcb6a3670058a8f4812c851518/Effects/JM_ana_Vectorscope.jsfx"
sha256 = "dd30d77fa2c2baf5e229916416922b8ab6a715c2b5760b82df801f30ecd2a139"
size = 20361
path = "JM_ana_Vectorscope.jsfx"

[[payload.files]]
url = "https://raw.githubusercontent.com/jozmac/reapack-jm/4f507485554c90dcb6a3670058a8f4812c851518/ThirdParty/Tale/rc_filter.jsfx-inc"
sha256 = "44646fff4d5c0c43daa8044e9d2adfa2e6724e469665923a64c67240a0751673"
size = 4984
path = "Tale/rc_filter.jsfx-inc"

[[payload.files]]
url = "https://raw.githubusercontent.com/jozmac/reapack-jm/4f507485554c90dcb6a3670058a8f4812c851518/ThirdParty/sault/st-oversampler.jsfx-inc"
sha256 = "aa1f4a518547c7f010c6f759c2627d829100c934a7b9a959c63828518fac899a"
size = 17120
path = "sault/st-oversampler.jsfx-inc"

[[payload.files]]
url = "https://raw.githubusercontent.com/jozmac/reapack-jm/4f507485554c90dcb6a3670058a8f4812c851518/ThirdParty/Tale/window.jsfx-inc"
sha256 = "ec0ca22629777f5838f7e484c00ec7ab580be50f19de4a76ab46400426281962"
size = 15108
path = "Tale/window.jsfx-inc"

[[payload.files]]
url = "https://raw.githubusercontent.com/jozmac/reapack-jm/4f507485554c90dcb6a3670058a8f4812c851518/ThirdParty/Tale/oversample.jsfx-inc"
sha256 = "14255d796eae939deea5447744e791087fb039e2b8a7c2c5b6a8fc62ef66776c"
size = 2844
path = "Tale/oversample.jsfx-inc"

[install]
entry = "JM_ana_Vectorscope.jsfx"
