schema = 1
id = "lv2.gxsloopyblue"
name = "GxSloopyBlue"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "GxPlugins"
tags = ["Distortion","Saturation"]
description = "GxSloopyBlue emulates an overdrive pedal that adds clipped harmonics and grit to instrument signals."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxsloopyblue/1.0.0.zip"
sha256 = "66d2ef6505244ff70c5f7c43fb2a20d7e4276e5fa05b001913484ee4c51d5646"
size = 833170

[install]
entry = "GxSloopyBlue.lv2/manifest.ttl"
