schema = 1
id = "lv2.gxfuzzfacefm"
name = "gx_fuzzfacefm"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "Guitarix"
tags = ["Distortion","Saturation"]
description = "gx_fuzzfacefm offers a fuzz-style effect that heavily clips instruments for dense harmonic coloration."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxfuzzfacefm/1.0.0.zip"
sha256 = "271200293e66a788b279c7909ed32534b8718ab4487c173421d73bfd9a701c65"
size = 4458196

[install]
entry = "gx_fuzzfacefm.lv2/manifest.ttl"
