schema = 1
id = "jsfx.joep.reabee"
name = "ReaBee"
version = "0.02"
format = "jsfx"
arch = ["arm64-v8a"]
manufacturer = "Joep Vanlier"
source = "https://github.com/JoepVanlier/JSFX"
tags = ["Utility"]
description = "ReaBee is an audio-processing utility designed to transform the incoming signal within a mix."
license = "custom"

[payload]
kind = "files"
size = 5827

[[payload.files]]
url = "https://raw.githubusercontent.com/JoepVanlier/JSFX/e3e559a28ebce112b967166afbec3c3e584bd25a/ReaBee/ReaBee.jsfx"
sha256 = "185e2c0c49b0bc5130c36dd23199dd6c7340bfe173d5bff2bfb9371d4cdaa54d"
size = 5827
path = "ReaBee.jsfx"

[install]
entry = "ReaBee.jsfx"
