schema = 1
id = "lv2.gxechocat"
name = "gxechocat"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "Guitarix"
tags = ["Delay"]
description = "Tape-delay simulation that creates repeating echoes with vintage-style coloration for guitar and other instrument signals."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxechocat/1.0.0.zip"
sha256 = "7aa71ca988c3e06877ed1b6798de710971247799e19090c58b53fd30ab1f969d"
size = 4741051

[install]
entry = "gxechocat.lv2/manifest.ttl"
