schema = 1
id = "lv2.gxechocat"
name = "gxechocat"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "Guitarix"
tags = ["Delay"]
description = "Tape-delay simulation that creates repeating echoes with vintage-style coloration for guitar and other instrument signals."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxechocat/1.0.0.zip"
sha256 = "da46530daaf49c10fa3ab11474eb2adef7623a3d0ed972981f72cf425ca8f470"
size = 4741047

[install]
entry = "gxechocat.lv2/manifest.ttl"
