schema = 1
id = "lv2.gxmuff"
name = "gx_muff"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "Guitarix"
tags = ["EQ"]
description = "gx_muff is an equalization effect for reshaping tonal balance across the instrument spectrum."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxmuff/1.0.0.zip"
sha256 = "c145e7dfc7d148e202287639bab4cfa7b227b3081a0b51d3e6a852a13146d00f"
size = 3524072

[install]
entry = "gx_muff.lv2/manifest.ttl"
