schema = 1
id = "lv2.gxmuff"
name = "gx_muff"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "Guitarix"
tags = ["EQ"]
description = "gx_muff is an equalization effect for reshaping tonal balance across the instrument spectrum."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxmuff/1.0.0.zip"
sha256 = "e31da0ecee4c6ba5dc7a31fbb4059bba17bdf901f2da93df55454bd34453c64b"
size = 3524074

[install]
entry = "gx_muff.lv2/manifest.ttl"
