schema = 1
id = "jsfx.tukan.la-1a"
name = "LA-1A (Tukan).jsfx"
version = "1.0.0"
format = "jsfx"
arch = ["arm64-v8a"]
manufacturer = "TukanStudios"
tags = ["jsfx"]
description = "LA-1A (Tukan)"
license = "custom"

[payload]
kind = "files"
size = 37865

[[payload.files]]
url = "https://raw.githubusercontent.com/TukanStudios/TUKAN_STUDIOS_PLUGINS/e400035bb4c02bf95c1adbef803cba2e4b6b36b5/LA-1A%20(Tukan)"
sha256 = "3ba303bf603f351554ed460a245d62354dd9fa909c0c304640a333255a045f1c"
size = 37865
path = "LA-1A (Tukan).jsfx"

[install]
entry = "LA-1A (Tukan).jsfx"
