schema = 1
id = "lv2.gxamp"
name = "gx_amp"
version = "1.0.0"
format = "lv2"
arch = ["arm64-v8a"]
manufacturer = "Guitarix"
tags = ["Simulator"]
description = "Amp/cabinet simulator."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxamp/1.0.0.zip"
sha256 = "0829bbcd6c1aafcc05c2c2c53232c7e247033fa3b1bfc802e5f4221a1cd51263"
size = 5347323

[install]
entry = "gx_amp.lv2/manifest.ttl"
