schema = 1
id = "lv2.gxamp"
name = "gx_amp"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "Guitarix"
tags = ["Amplifier","Cabinet"]
description = "gx_amp combines modeled guitar amplification and speaker-cabinet coloration in one processor."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxamp/1.0.0.zip"
sha256 = "e90187ceb98fb1e4224bed908f34983146a51b8f35fe5aa8666f80795b4401d9"
size = 5347289

[install]
entry = "gx_amp.lv2/manifest.ttl"
