schema = 1
id = "lv2.gxdigitaldelay"
name = "gx_digital_delay"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "Guitarix"
tags = ["Delay"]
description = "gx_digital_delay creates clean digital echoes and repeating patterns from an incoming signal."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxdigitaldelay/1.0.0.zip"
sha256 = "ac9bbe1704e04706ef8b56e2457d6ea3af3af24464b7dd8a24f6f0776381ad05"
size = 5192967

[install]
entry = "gx_digital_delay.lv2/manifest.ttl"
