schema = 1
id = "lv2.gxmetalamp"
name = "gxmetal_amp"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "Guitarix"
tags = ["Amplifier","Cabinet","Distortion"]
description = "gxmetal_amp provides high-gain amplifier and speaker coloration for shaping heavy guitar tones."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxmetalamp/1.0.0.zip"
sha256 = "cb8622cbd26bfe0dd7ef9d3aa977fc4983cf3f4ca0b509774ff6e7124fba7ba0"
size = 4225408

[install]
entry = "gxmetal_amp.lv2/manifest.ttl"
