schema = 1
id = "lv2.gxexpander"
name = "gx_expander"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "Guitarix"
tags = ["Expander"]
description = "Dynamics processor that expands signal range or gates low-level noise to tighten pauses and transient articulation."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxexpander/1.0.0.zip"
sha256 = "59d57358fb4f4ee055d330a7b0616888d383b2daeeb96ff2dfefc847b7a64a42"
size = 4384304

[install]
entry = "gx_expander.lv2/manifest.ttl"
