schema = 1
id = "lv2.gxphaser"
name = "gx_phaser"
version = "1.0.0"
format = "lv2"
arch = ["arm64-v8a"]
manufacturer = "Guitarix"
tags = ["Phaser"]
description = "Phaser effect."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxphaser/1.0.0.zip"
sha256 = "a038e8b03f55c3651fc52e3db7ec06d76fdd0ebf3bbb183b4b7a4a817a644609"
size = 4377313

[install]
entry = "gx_phaser.lv2/manifest.ttl"
