schema = 1
id = "lv2.gxflanger"
name = "gx_flanger"
version = "1.0.0"
format = "lv2"
arch = ["arm64-v8a"]
manufacturer = "Guitarix"
tags = ["Flanger"]
description = "Flanger effect."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxflanger/1.0.0.zip"
sha256 = "a610b2a40b8f75380c6bc35a5654850a71e866b2db9b0f7a2496cdaca06cc371"
size = 4433291

[install]
entry = "gx_flanger.lv2/manifest.ttl"
