schema = 1
id = "lv2.xtinyterror"
name = "XTinyTerror"
version = "1.0.0"
format = "lv2"
source = "https://github.com/brummer10/XTinyTerror.lv2"
arch = ["arm64-v8a"]
manufacturer = "brummer10"
tags = ["Amplifier","Distortion"]
description = "XTinyTerror emulates a compact valve guitar amplifier to add gain, compression, and harmonic character."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.xtinyterror/1.0.0.zip"
sha256 = "9846841bd1125824ae7854da0aa204f40a1230841df114e984d961b9c2a9b989"
size = 842001

[install]
entry = "XTinyTerror.lv2/manifest.ttl"
