schema = 1
id = "jsfx.tilr.quickfilter"
name = "QuickFilter.jsfx"
version = "1.1"
format = "jsfx"
arch = ["arm64-v8a"]
manufacturer = "tilr"
tags = ["jsfx"]
description = "QuickFilter"
license = "custom"

[payload]
kind = "files"
size = 32434

[[payload.files]]
url = "https://raw.githubusercontent.com/tiagolr/tilr_jsfx/3713438b8441baf7a0cb2e167c85e92605e7f4c1/Filter/QuickFilter.jsfx"
sha256 = "e2032894546d784272643ae0ac16c5c75886725ca1c9f9ca1cf8ca3a338857b3"
size = 1957
path = "QuickFilter.jsfx"

[[payload.files]]
url = "https://raw.githubusercontent.com/tiagolr/tilr_jsfx/3713438b8441baf7a0cb2e167c85e92605e7f4c1/Filter/qfilter/qf.svf_filter.jsfx-inc"
sha256 = "6bb6670c831267b8a75f6a0515b8e4ba350c3c138a813057ab332016dcd50b79"
size = 30477
path = "qfilter/qf.svf_filter.jsfx-inc"

[install]
entry = "QuickFilter.jsfx"
