schema = 1
id = "lv2.gxtremolo"
name = "gx_tremolo"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "Guitarix"
tags = ["Modulation"]
description = "gx_tremolo produces periodic amplitude changes for a pulsing variation in instrument volume."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxtremolo/1.0.0.zip"
sha256 = "d8dfdd810edb4b36454c1feb7c6c74474fe69c3eec1932d3bea58cd396d2a5c5"
size = 4508647

[install]
entry = "gx_tremolo.lv2/manifest.ttl"
