schema = 1
id = "lv2.gxheathkit"
name = "GxHeathkit"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "GxPlugins"
tags = ["Distortion"]
description = "Distortion Booster Pedal simulation."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxheathkit/1.0.0.zip"
sha256 = "40fc2214c112075e700ab6ecc46819f3f886205571f1b009f6d83dd5704ff4a9"
size = 1503348

[install]
entry = "GxHeathkit.lv2/manifest.ttl"
