schema = 1
id = "lv2.gxzitarev1"
name = "gx_zita_rev1"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "Guitarix"
tags = ["Reverb"]
description = "gx_zita_rev1 generates spacious reverberation with a sustained decay for adding depth and ambience."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxzitarev1/1.0.0.zip"
sha256 = "7d9465132649854952e574a17270626ef6d0156af6b04b7b156fdf8e6b32296a"
size = 3480401

[install]
entry = "gx_zita_rev1.lv2/manifest.ttl"
