schema = 1
id = "lv2.gxfz1s"
name = "GxFz1s"
version = "1.0.0"
format = "lv2"
arch = ["arm64-v8a"]
manufacturer = "GxPlugins"
tags = ["Distortion"]
description = "Vintage Fuzz Pedal simulation."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxfz1s/1.0.0.zip"
sha256 = "2efcb9b838ba8b578f68151054ffbf20f7c35acabbe66acc25b5f7c74b5c4486"
size = 1576275

[install]
entry = "GxFz1s.lv2/manifest.ttl"
