schema = 1
id = "lv2.gxfz1s"
name = "GxFz1s"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "GxPlugins"
tags = ["Distortion","Saturation"]
description = "GxFz1s recreates vintage pedal fuzz for sustained, saturated instrument sounds with pronounced clipping."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxfz1s/1.0.0.zip"
sha256 = "7fc13c58aeb3628280d99f03dab93af95f3baf52f5eeea4ae4bedb2265ba91eb"
size = 1576277

[install]
entry = "GxFz1s.lv2/manifest.ttl"
