schema = 1
id = "jsfx.jozmac.jm-gen-dpoae-canceller"
name = "JM_gen_DPOAE_Canceller"
version = "1.0"
format = "jsfx"
arch = ["arm64-v8a"]
manufacturer = "Jozef Mackowiak"
source = "https://github.com/jozmac/reapack-jm"
tags = ["Synth","Utility"]
description = "A specialized signal generator intended for DPOAE cancellation work in audio testing contexts."
license = "custom"

[payload]
kind = "files"
size = 73669

[[payload.files]]
url = "https://raw.githubusercontent.com/jozmac/reapack-jm/4f507485554c90dcb6a3670058a8f4812c851518/Effects/JM_gen_DPOAE_Canceller.jsfx"
sha256 = "7715178316a6375806d92991f34bc2a0143f131b00d7434db44e05ce8c392475"
size = 46727
path = "JM_gen_DPOAE_Canceller.jsfx"

[[payload.files]]
url = "https://raw.githubusercontent.com/jozmac/reapack-jm/4f507485554c90dcb6a3670058a8f4812c851518/ThirdParty/Tale/poly_blep.jsfx-inc"
sha256 = "0f2dc90d0d8110fc37ba788ca4da43cb5564880dc5b18cd6ed4e45a67e03d40f"
size = 26942
path = "Tale/poly_blep.jsfx-inc"

[install]
entry = "JM_gen_DPOAE_Canceller.jsfx"
