schema = 1
id = "jsfx.tukan.lexikan"
name = "Lexikan (Tukan).jsfx"
version = "1.0.0"
format = "jsfx"
arch = ["arm64-v8a"]
manufacturer = "TukanStudios"
tags = ["jsfx"]
description = "Lexikan (Tukan)"
license = "custom"

[payload]
kind = "files"
size = 72658

[[payload.files]]
url = "https://raw.githubusercontent.com/TukanStudios/TUKAN_STUDIOS_PLUGINS/e400035bb4c02bf95c1adbef803cba2e4b6b36b5/Lexikan%20(Tukan)"
sha256 = "18207c238382645e12795be4fb317948a09fff3df26e5986c43dce154bcc44da"
size = 71662
path = "Lexikan (Tukan).jsfx"

[[payload.files]]
url = "https://raw.githubusercontent.com/TukanStudios/TUKAN_STUDIOS_PLUGINS/e400035bb4c02bf95c1adbef803cba2e4b6b36b5/smoother.jsfx-inc"
sha256 = "d77e47a1f018d0862babd4cd7be447a66bd9748262d5967912d952ec375ba880"
size = 996
path = "smoother.jsfx-inc"

[install]
entry = "Lexikan (Tukan).jsfx"
