schema = 1
id = "lv2.gxsvt"
name = "GxSVT"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "GxPlugins"
tags = ["Simulator"]
description = "Tube based Bass preamp simulation."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxsvt/1.0.0.zip"
sha256 = "5fca2eda5242bced72bebff37a2bbcac1ef8f14d41c8b6213f8e3c613f59b1ff"
size = 1194317

[install]
entry = "GxSVT.lv2/manifest.ttl"
