schema = 1
id = "lv2.gxrangem"
name = "gx_rangem"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "Guitarix"
tags = ["Filter"]
description = "gx_rangem emphasizes a focused frequency range to produce a brighter, more forward instrument tone."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxrangem/1.0.0.zip"
sha256 = "af359b8e2169dd0a7115945f9bffa9263a5d84ca07222340f8d8533b16061976"
size = 4254060

[install]
entry = "gx_rangem.lv2/manifest.ttl"
