schema = 1
id = "lv2.gxeternity"
name = "GxEternity"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "GxPlugins"
tags = ["Distortion"]
description = "This low compression overdrive pedal is perfect for any style of music that requires natural sounding overdrive."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxeternity/1.0.0.zip"
sha256 = "7e785997f9dfe857e601123310d788421704ea20f4f6832bf75f74e83ce0005a"
size = 836475

[install]
entry = "GxEternity.lv2/manifest.ttl"
