schema = 1
id = "lv2.gxeternity"
name = "GxEternity"
version = "1.0.0"
format = "lv2"
arch = ["arm64-v8a"]
manufacturer = "GxPlugins"
tags = ["Distortion"]
description = "This low compression overdrive pedal is perfect for any style of music that requires natural sounding overdrive."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxeternity/1.0.0.zip"
sha256 = "87e516efaca25102c79177940673a1ea4c491df821fc093dfac28c0e54b6a5a8"
size = 836476

[install]
entry = "GxEternity.lv2/manifest.ttl"
