schema = 1
id = "lv2.gxvintagefuzzmaster"
name = "GxVintageFuzzMaster"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "GxPlugins"
tags = ["Distortion"]
description = "Simulation of the Vintage Fuzz Master Pedal."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxvintagefuzzmaster/1.0.0.zip"
sha256 = "ea8c3bec9482a56984267da5931724ed7a95e6fb905f3d889d6d4b4d2c728819"
size = 1567618

[install]
entry = "GxVintageFuzzMaster.lv2/manifest.ttl"
