schema = 1
id = "lv2.gxvibe"
name = "gx_vibe"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "Guitarix"
tags = ["Modulation","Phaser"]
description = "gx_vibe adds cyclical, phase-like movement associated with classic vibe modulation effects."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxvibe/1.0.0.zip"
sha256 = "975771fa0b7feb078ebb56104ae2b31a1fe862fd68dc9fcf095e7e4fc361c4bf"
size = 5897540

[install]
entry = "gx_vibe.lv2/manifest.ttl"
