schema = 1
id = "lv2.gxreverb"
name = "gx_reverb"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "Guitarix"
tags = ["Reverb"]
description = "gx_reverb adds decaying reflections that place an instrument signal in a simulated acoustic space."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxreverb/1.0.0.zip"
sha256 = "e07b92841f40fb0661bda6f70d35df747a7e2d020cdbe845e540604acbbf3c85"
size = 4950199

[install]
entry = "gx_reverb.lv2/manifest.ttl"
