schema = 1
id = "lv2.boops"
name = "B.Oops"
version = "1.0.1"
format = "lv2"
source = "https://github.com/sjaehn/BOops"
arch = ["arm64-v8a"]
manufacturer = "Sven Jaehnichen"
tags = ["Envelope","Delay","Sequencer","Utility"]
description = "Pattern-based creative effect with samples, sequencing, and extensive modulation for experimental sound design."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.boops/1.0.1.zip"
sha256 = "d1b91c1f72ae1a6c7699cbc6e49b407b166027b84f07bbcb076b58a695432280"
size = 2347755

[install]
entry = "BOops.lv2/manifest.ttl"
