schema = 1
id = "jsfx.joep.saike-nostalgizer"
name = "saike_nostalgizer.jsfx"
version = "0.15"
format = "jsfx"
arch = ["arm64-v8a"]
manufacturer = "Joep Vanlier"
tags = ["jsfx"]
description = "Saike / Nostalgizer / Lo-Fi (BETA)"
license = "custom"

[payload]
kind = "files"
size = 70723

[[payload.files]]
url = "https://raw.githubusercontent.com/JoepVanlier/JSFX/4cd926c66ef6e52d3ab54e3c4fe96def795c0869/Nostalgizer/saike_nostalgizer.jsfx"
sha256 = "dd52e653d2e1af84b3560db9037f2bee6036e16c6c6eeb16b0f86564aff8a88c"
size = 31625
path = "saike_nostalgizer.jsfx"

[[payload.files]]
url = "https://raw.githubusercontent.com/JoepVanlier/JSFX/4cd926c66ef6e52d3ab54e3c4fe96def795c0869/Nostalgizer/nostalgizer_dependencies/saike_nostalgizer_widgets.jsfx-inc"
sha256 = "954b016479dee3c1a497c943780bfb4960c9f6be41fc4107f0f6837183e1b14e"
size = 39098
path = "nostalgizer_dependencies/saike_nostalgizer_widgets.jsfx-inc"

[install]
entry = "saike_nostalgizer.jsfx"
