schema = 1
id = "lv2.gxtubedelay"
name = "gxtubedelay"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "Guitarix"
tags = ["Delay","Saturation"]
description = "gxtubedelay creates timed echoes with tube-like harmonic coloration in the repeated signal."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxtubedelay/1.0.0.zip"
sha256 = "5b9c187b44d0bc62c3662721950e4cbcac7a3b947da3700c83e2a7731ddf5b86"
size = 4560556

[install]
entry = "gxtubedelay.lv2/manifest.ttl"
