schema = 1
id = "lv2.doubletracker"
name = "doubletracker"
version = "1.0.0"
format = "lv2"
source = "https://github.com/Varcain/doubletracker.lv2"
arch = ["arm64-v8a"]
manufacturer = "Varcain"
tags = ["Delay","Stereo","Utility"]
description = "Emulated dual-take track, best with headphones."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.doubletracker/1.0.0.zip"
sha256 = "38b8364551602da821f4557eb9a5a0cadf273d1c5160042599fff677a93ebb22"
size = 105474

[install]
entry = "doubletracker.lv2/manifest.ttl"
