schema = 1
id = "lv2.fourkeq2"
name = "4K EQ 2"
version = "1.0.0"
format = "lv2"
arch = ["arm64-v8a"]
manufacturer = "Dusk Audio"
tags = ["EQ","Filter"]
description = "British console-style four-band equalizer with high-pass and low-pass filters."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.fourkeq2/1.0.0.zip"
sha256 = "29156ab2f78d1c7b511cb6aa5a9d35e11214caed04e488bdb21a5a0a63913553"
size = 918330

[install]
entry = "four_k_eq_2.lv2/manifest.ttl"
