schema = 1
id = "jsfx.joep.squashman"
name = "Squashman"
version = "0.86"
format = "jsfx"
arch = ["arm64-v8a"]
manufacturer = "Joep Vanlier"
source = "https://github.com/JoepVanlier/JSFX"
tags = ["Compressor","Dynamics"]
description = "Squashman compresses signal dynamics to reduce level variation and create a denser, more controlled sound."
license = "custom"

[payload]
kind = "files"
size = 423839

[[payload.files]]
url = "https://raw.githubusercontent.com/JoepVanlier/JSFX/1b406a7932bb8b5b54858f7814131760eda9708c/Squashman/Squashman.jsfx"
sha256 = "3f405fc505d1eb2725f62cfe295ee71d7fb0ee2f0400f9aaceb2764701dcc6af"
size = 201115
path = "Squashman.jsfx"

[[payload.files]]
url = "https://raw.githubusercontent.com/JoepVanlier/JSFX/1b406a7932bb8b5b54858f7814131760eda9708c/Squashman/Squashman_Dependencies/envelopes.jsfx-inc"
sha256 = "74ab94a334ffea9fa8ee328d41450fab84e27a6c62909954169256baa5eb45f5"
size = 37651
path = "Squashman_Dependencies/envelopes.jsfx-inc"

[[payload.files]]
url = "https://raw.githubusercontent.com/JoepVanlier/JSFX/1b406a7932bb8b5b54858f7814131760eda9708c/Squashman/Squashman_Dependencies/squashman2.png"
sha256 = "a807cbd934df2f59de8eca4910a29bd99a0bb0a72624e5aa10acf1941a243fe7"
size = 907
path = "Squashman_Dependencies/squashman2.png"

[[payload.files]]
url = "https://raw.githubusercontent.com/JoepVanlier/JSFX/1b406a7932bb8b5b54858f7814131760eda9708c/Squashman/Squashman_Dependencies/squashman3.png"
sha256 = "d2512dd269ec8aab7c79b477e67d3b8d77b9f511f1aad221606210d4e8fd3d07"
size = 888
path = "Squashman_Dependencies/squashman3.png"

[[payload.files]]
url = "https://raw.githubusercontent.com/JoepVanlier/JSFX/1b406a7932bb8b5b54858f7814131760eda9708c/Squashman/Squashman_Dependencies/squashman_agc.jsfx-inc"
sha256 = "d64c518ccd09bef20b7dcd623ee441f73e2cbc433a2f5997de5281738d9112a1"
size = 2534
path = "Squashman_Dependencies/squashman_agc.jsfx-inc"

[[payload.files]]
url = "https://raw.githubusercontent.com/JoepVanlier/JSFX/1b406a7932bb8b5b54858f7814131760eda9708c/Squashman/Squashman_Dependencies/squashman_upsamplers.jsfx-inc"
sha256 = "c254b307e71bc409106230ca26907f0f0eaba9522b7ca76139022bb427811a66"
size = 126953
path = "Squashman_Dependencies/squashman_upsamplers.jsfx-inc"

[[payload.files]]
url = "https://raw.githubusercontent.com/JoepVanlier/JSFX/1b406a7932bb8b5b54858f7814131760eda9708c/Squashman/Squashman_Dependencies/widgetdata.jsfx-inc"
sha256 = "c22d07d9f5a4cbd58dd4e6b7d4f121ee2237b3d23701177956030a9d1982311b"
size = 9303
path = "Squashman_Dependencies/widgetdata.jsfx-inc"

[[payload.files]]
url = "https://raw.githubusercontent.com/JoepVanlier/JSFX/1b406a7932bb8b5b54858f7814131760eda9708c/Squashman/Squashman_Dependencies/widgets.jsfx-inc"
sha256 = "57c462a57b6269a16bad7e2595543ddfcc5812a42e5931a490b9de33648bf854"
size = 44488
path = "Squashman_Dependencies/widgets.jsfx-inc"

[install]
entry = "Squashman.jsfx"
