schema = 1
id = "lv2.gxduckdelay"
name = "gx_duck_delay"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "Guitarix"
tags = ["Delay"]
description = "Envelope-controlled ducking delay."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxduckdelay/1.0.0.zip"
sha256 = "465bdf273ee183fe9e7fc27009ec11860ea62a08a1bc749d116a89329e3726af"
size = 4358312

[install]
entry = "gx_duck_delay.lv2/manifest.ttl"
