schema = 1
id = "lv2.gxswitchedtremolo"
name = "gx_switched_tremolo"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "Guitarix"
tags = ["Modulation"]
description = "gx_switched_tremolo rhythmically switches signal level to create a pronounced tremolo pulse."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxswitchedtremolo/1.0.0.zip"
sha256 = "69633d26dd2cdb26f85e81b83edae1b1cf91f53c43ace5f25d55ca25d78ca22a"
size = 5177877

[install]
entry = "gx_switched_tremolo.lv2/manifest.ttl"
