schema = 1
id = "lv2.gxchorus"
name = "gx_chorus"
version = "1.0.0"
format = "lv2"
arch = ["arm64-v8a"]
manufacturer = "Guitarix"
tags = ["Chorus"]
description = "Chorus effect."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxchorus/1.0.0.zip"
sha256 = "9ccdac45c7681c9a9b5572c318d894ff98262545aff53a702f9878cc8c4a8fad"
size = 5863348

[install]
entry = "gx_chorus.lv2/manifest.ttl"
