schema = 1
id = "lv2.gxdetune"
name = "gx_detune"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "Guitarix"
tags = ["Pitch","Modulation"]
description = "gx_detune shifts pitch slightly to create detuned doubling and a broader modulation-like sound."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxdetune/1.0.0.zip"
sha256 = "d6803c54bb77c5bb6d33c079c8318331deed38f520fc821fb9fc336b3247a219"
size = 5064622

[install]
entry = "gx_detune.lv2/manifest.ttl"
