schema = 1
id = "jsfx.geraint.stereo-alignment-delay"
name = "Stereo Alignment Delay"
version = "1.3.1"
format = "jsfx"
arch = ["arm64-v8a"]
manufacturer = "Geraint Luff"
source = "https://github.com/geraintluff/jsfx"
tags = ["Delay","Stereo","Utility"]
description = "Stereo Alignment Delay offsets channel timing to align left and right stereo signals."
license = "custom"

[payload]
kind = "files"
size = 117337

[[payload.files]]
url = "https://raw.githubusercontent.com/geraintluff/jsfx/e98d64401ba57590b7ea0d3592675accb43667da/releases/Stereo-Alignment-Delay/1.3.1/Stereo-Alignment-Delay/ui-lib.jsfx-inc"
sha256 = "e25d3fea9cb2009cfa8212088fa53f3ec84b8136cc04e0599d6318b621cac113"
size = 96978
path = "ui-lib.jsfx-inc"

[[payload.files]]
url = "https://raw.githubusercontent.com/geraintluff/jsfx/e98d64401ba57590b7ea0d3592675accb43667da/releases/Stereo-Alignment-Delay/1.3.1/Stereo-Alignment-Delay/Stereo%20Alignment%20Delay.jsfx"
sha256 = "3b4495b4bd749abbe66251447ba27a8eb5332716dc8a0e0045427807d2e43893"
size = 20359
path = "Stereo Alignment Delay.jsfx"

[install]
entry = "Stereo Alignment Delay.jsfx"
