schema = 1
id = "lv2.gxfumaster"
name = "gx_fumaster"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "Guitarix"
tags = ["Distortion"]
description = "gx_fumaster is a drive effect that adds clipped harmonics and forceful distortion to instrument signals."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxfumaster/1.0.0.zip"
sha256 = "8340c6df6820b0891062c547e033dede6eeee90e43cb39a61df2a39baf9f03d6"
size = 4270876

[install]
entry = "gx_fumaster.lv2/manifest.ttl"
