schema = 1
id = "lv2.gxfumaster"
name = "gx_fumaster"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "Guitarix"
tags = ["Distortion"]
description = "gx_fumaster is a drive effect that adds clipped harmonics and forceful distortion to instrument signals."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxfumaster/1.0.0.zip"
sha256 = "1c36c13440ee8cc431b10121c0fc9128a1b19fed5f8002c1a92786bf765ba2d1"
size = 4270878

[install]
entry = "gx_fumaster.lv2/manifest.ttl"
