schema = 1
id = "lv2.fil4"
name = "fil4"
version = "1.0.0"
format = "lv2"
arch = ["arm64-v8a"]
manufacturer = "x42"
tags = ["EQ","Filter"]
description = "Parametric equalizer with selectable high-pass, low-pass, and filter shaping."
license = "GPL-2.0-only"

[payload]
kind = "archive"
url = "../../payload/lv2.fil4/1.0.0.zip"
sha256 = "f25a3a11eeab1845dc4faba1db5b64d9b25bd7eddbe6cb3fd53f7ee2b8bc984c"
size = 461706

[install]
entry = "fil4.lv2/manifest.ttl"
