schema = 1
id = "lv2.fil4"
name = "fil4"
version = "1.0.0"
format = "lv2"
source = "https://github.com/x42/fil4.lv2"
arch = ["arm64-v8a"]
manufacturer = "x42"
tags = ["EQ","Filter"]
description = "Parametric equalizer with selectable high-pass, low-pass, and filter shaping."
license = "GPL-2.0-only"

[payload]
kind = "archive"
url = "../../payload/lv2.fil4/1.0.0.zip"
sha256 = "cad49d9670ff0cd9b390b7eeddde8ef65e2174f4176636716e3ac52d5d513e93"
size = 461706

[install]
entry = "fil4.lv2/manifest.ttl"
