schema = 1
id = "jsfx.joep.saike-fmfilter2"
name = "Saike_FMFilter2.jsfx"
version = "0.23"
format = "jsfx"
arch = ["arm64-v8a"]
manufacturer = "Joep Vanlier"
tags = ["jsfx"]
description = "Saike FM Filter 2"
license = "custom"

[payload]
kind = "files"
size = 97413

[[payload.files]]
url = "https://raw.githubusercontent.com/JoepVanlier/JSFX/1e972149df86bd69cc3fab52af855f29aaf16021/Yutani/Saike_FMFilter2.jsfx"
sha256 = "200472af45f966aabff5339aa019976f410b7bdcde7a3f54b3679e33cdeb3924"
size = 97413
path = "Saike_FMFilter2.jsfx"

[install]
entry = "Saike_FMFilter2.jsfx"
