schema = 1
id = "lv2.gxbajatubedriver"
name = "GxBaJaTubeDriver"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "GxPlugins"
tags = ["Distortion"]
description = "Tube based overdrive pedal simulation."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxbajatubedriver/1.0.0.zip"
sha256 = "cda8daa8cbf3058a190a3ce197f285213c4792e040d5a4f84913a45a383e2099"
size = 827957

[install]
entry = "GxBaJaTubeDriver.lv2/manifest.ttl"
