schema = 1
id = "lv2.gxbajatubedriver"
name = "GxBaJaTubeDriver"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "GxPlugins"
tags = ["Distortion"]
description = "Tube based overdrive pedal simulation."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxbajatubedriver/1.0.0.zip"
sha256 = "6722dbf1e2405e6ec56ae9590127b980a9e35155726fc7174c855fa5232746bb"
size = 827958

[install]
entry = "GxBaJaTubeDriver.lv2/manifest.ttl"
