schema = 1
id = "jsfx.joep.saike-nuker"
name = "saike_nuker.jsfx"
version = "0.04"
format = "jsfx"
arch = ["arm64-v8a"]
manufacturer = "Joep Vanlier"
tags = ["jsfx"]
description = "Saike Nuker (EARLY ALPHA - DO NOT USE)"
license = "custom"

[payload]
kind = "files"
size = 42985

[[payload.files]]
url = "https://raw.githubusercontent.com/JoepVanlier/JSFX/b9d7f28b5ed6d4a4c2a8216d91fbb3e1acefe69f/Nuker/saike_nuker.jsfx"
sha256 = "cd67fa9e251e11a5880fee160edd16c84344fbecb78f06f6f7ee7e3754779538"
size = 5897
path = "saike_nuker.jsfx"

[[payload.files]]
url = "https://raw.githubusercontent.com/JoepVanlier/JSFX/b9d7f28b5ed6d4a4c2a8216d91fbb3e1acefe69f/Nuker/Nuker_Dependencies/Nuker_SVFs.jsfx-inc"
sha256 = "86966d5aab6994a32d4930bc66781356293ca2c122948365b79172df35a2a27b"
size = 2802
path = "Nuker_Dependencies/Nuker_SVFs.jsfx-inc"

[[payload.files]]
url = "https://raw.githubusercontent.com/JoepVanlier/JSFX/b9d7f28b5ed6d4a4c2a8216d91fbb3e1acefe69f/Nuker/Nuker_Dependencies/Nuker_buffers.jsfx-inc"
sha256 = "427925b72fb069c3fbf577483cbcff6315211689fdb303c8ba0f480158c3b709"
size = 3125
path = "Nuker_Dependencies/Nuker_buffers.jsfx-inc"

[[payload.files]]
url = "https://raw.githubusercontent.com/JoepVanlier/JSFX/b9d7f28b5ed6d4a4c2a8216d91fbb3e1acefe69f/Nuker/Nuker_Dependencies/Nuker_cabs.jsfx-inc"
sha256 = "8547779f9ce5e36c45f45e42cfa7880b6ab010f12b1690de3f9aba690f387b5c"
size = 18860
path = "Nuker_Dependencies/Nuker_cabs.jsfx-inc"

[[payload.files]]
url = "https://raw.githubusercontent.com/JoepVanlier/JSFX/b9d7f28b5ed6d4a4c2a8216d91fbb3e1acefe69f/Nuker/Nuker_Dependencies/Nuker_compressor.jsfx-inc"
sha256 = "f6f8f4e208df5c0bd1b23b94d357e1f8dc50bd312158b18f881bb9b5526c5f3a"
size = 2187
path = "Nuker_Dependencies/Nuker_compressor.jsfx-inc"

[[payload.files]]
url = "https://raw.githubusercontent.com/JoepVanlier/JSFX/b9d7f28b5ed6d4a4c2a8216d91fbb3e1acefe69f/Nuker/Nuker_Dependencies/Nuker_interpolators.jsfx-inc"
sha256 = "f00612e704f06dd4ec94578c0ba28adc5f031ef5f9fcd2c05d4998a36206fcac"
size = 1774
path = "Nuker_Dependencies/Nuker_interpolators.jsfx-inc"

[[payload.files]]
url = "https://raw.githubusercontent.com/JoepVanlier/JSFX/b9d7f28b5ed6d4a4c2a8216d91fbb3e1acefe69f/Nuker/Nuker_Dependencies/Nuker_sph.jsfx-inc"
sha256 = "44159725f6b8b1c0f9ef2d40393987a4d4850fde10f7ef05113b19af565bdaec"
size = 7339
path = "Nuker_Dependencies/Nuker_sph.jsfx-inc"

[[payload.files]]
url = "https://raw.githubusercontent.com/JoepVanlier/JSFX/b9d7f28b5ed6d4a4c2a8216d91fbb3e1acefe69f/Nuker/Nuker_Dependencies/Nuker_warmth.jsfx-inc"
sha256 = "580677fcfcea599b71ec96341714fe8bbe56c6ea31890c81a952c39082c16b80"
size = 1001
path = "Nuker_Dependencies/Nuker_warmth.jsfx-inc"

[install]
entry = "saike_nuker.jsfx"
