schema = 1
id = "lv2.gxepic"
name = "GxEpic"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "GxPlugins"
tags = ["Distortion"]
description = "Simulation of a class A electric guitar valve amplifier."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxepic/1.0.0.zip"
sha256 = "573520a9175e6d61eb21f7717d2e7fe3d3da2f419b4bd7b2f9809ff8f1de91b7"
size = 882920

[install]
entry = "GxEpic.lv2/manifest.ttl"
