schema = 1
id = "lv2.gxepic"
name = "GxEpic"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "GxPlugins"
tags = ["Distortion"]
description = "Simulation of a class A electric guitar valve amplifier."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxepic/1.0.0.zip"
sha256 = "3c05babe5a0a774ebd80e0e68bba62fc1352e20628da4e9c1abfec47fadd5179"
size = 882922

[install]
entry = "GxEpic.lv2/manifest.ttl"
