schema = 1
id = "lv2.gxampstereo"
name = "gx_amp_stereo"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "Guitarix"
tags = ["Amplifier","Cabinet","Stereo"]
description = "gx_amp_stereo applies modeled guitar amplifier and cabinet coloration to stereo signals."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxampstereo/1.0.0.zip"
sha256 = "17a213c32cf87fedeb7a44f02ba9795760a808fc53308061c76aed54c410d5b2"
size = 5393770

[install]
entry = "gx_amp_stereo.lv2/manifest.ttl"
