schema = 1
id = "lv2.gxtubetremelo"
name = "gxtubetremelo"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "Guitarix"
tags = ["Modulation","Saturation"]
description = "gxtubetremelo applies periodic level modulation with tube-style coloration for a pulsing tone."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxtubetremelo/1.0.0.zip"
sha256 = "d17d49548c05e507ef04067b6b42ce39e0085b7871cc6082462160987e814413"
size = 4937669

[install]
entry = "gxtubetremelo.lv2/manifest.ttl"
