schema = 1
id = "jsfx.jozmac.jm-fx-filter-vowel"
name = "JM_fx_Filter_Vowel.jsfx"
version = "1.0"
format = "jsfx"
arch = ["arm64-v8a"]
manufacturer = "Jozef Mackowiak"
tags = ["jsfx"]
description = "Vowel Filter v2 [JM]"
license = "custom"

[payload]
kind = "files"
size = 20698

[[payload.files]]
url = "https://raw.githubusercontent.com/jozmac/reapack-jm/4f507485554c90dcb6a3670058a8f4812c851518/Effects/JM_fx_Filter_Vowel.jsfx"
sha256 = "9cf093d701bd84425e5e9651df2b7f2be20dd838235e98cec420867f56a03a10"
size = 11516
path = "JM_fx_Filter_Vowel.jsfx"

[[payload.files]]
url = "https://raw.githubusercontent.com/jozmac/reapack-jm/4f507485554c90dcb6a3670058a8f4812c851518/ThirdParty/Tale/rbj_filter.jsfx-inc"
sha256 = "f6493654e2d180f5ec9096668097d510dd09e7f893d52a9e94b9b6696b930a24"
size = 9182
path = "Tale/rbj_filter.jsfx-inc"

[install]
entry = "JM_fx_Filter_Vowel.jsfx"
