schema = 1
id = "jsfx.jozmac.jm-util-proximity"
name = "JM_util_Proximity"
version = "1.0"
format = "jsfx"
arch = ["arm64-v8a"]
manufacturer = "Jozef Mackowiak"
source = "https://github.com/jozmac/reapack-jm"
tags = ["Utility"]
description = "An audio utility designed to alter the signal's perceived sense of proximity or distance."
license = "custom"

[payload]
kind = "files"
size = 23880

[[payload.files]]
url = "https://raw.githubusercontent.com/jozmac/reapack-jm/4f507485554c90dcb6a3670058a8f4812c851518/Effects/JM_util_Proximity.jsfx"
sha256 = "8b96d8693d0f363eee753a398a9f7b6ad8210f2aba86f6fe78a8398712656adb"
size = 14698
path = "JM_util_Proximity.jsfx"

[[payload.files]]
url = "https://raw.githubusercontent.com/jozmac/reapack-jm/4f507485554c90dcb6a3670058a8f4812c851518/ThirdParty/Tale/rbj_filter.jsfx-inc"
sha256 = "f6493654e2d180f5ec9096668097d510dd09e7f893d52a9e94b9b6696b930a24"
size = 9182
path = "Tale/rbj_filter.jsfx-inc"

[install]
entry = "JM_util_Proximity.jsfx"
