schema = 1
id = "lv2.gxw20"
name = "gx_w20"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "Guitarix"
tags = ["Simulator"]
description = "W20-style tube preamp and tone stack."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxw20/1.0.0.zip"
sha256 = "db3cc39cbeac4437891595322540174176e47aa842ee8b7bddbe56e126dc1cdb"
size = 3490033

[install]
entry = "gx_w20.lv2/manifest.ttl"
