schema = 1
id = "lv2.gxw20"
name = "gx_w20"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "Guitarix"
tags = ["Simulator"]
description = "W20-style tube preamp and tone stack."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxw20/1.0.0.zip"
sha256 = "15b23605f8680707ca8febcf1bbc827460e1a950f1e896442e8406714f5c0097"
size = 3490030

[install]
entry = "gx_w20.lv2/manifest.ttl"
