schema = 1
id = "lv2.gxcabinet"
name = "gx_cabinet"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "Guitarix"
tags = ["Cabinet","Filter"]
description = "gx_cabinet simulates the frequency coloration of a guitar speaker cabinet for amp or instrument signals."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxcabinet/1.0.0.zip"
sha256 = "a3e566712118b93419d350d51e241683a10bc4921959da3e30a61236ad656e84"
size = 4916038

[install]
entry = "gx_cabinet.lv2/manifest.ttl"
