schema = 1
id = "lv2.gxmbreverb"
name = "gx_mbreverb"
version = "1.0.0"
format = "lv2"
arch = ["arm64-v8a"]
manufacturer = "Guitarix"
tags = ["Reverb"]
description = "Reverb effect."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxmbreverb/1.0.0.zip"
sha256 = "e1203f0d42efbc86875855dd0f16d7405078b940ab0d592c8ae66c8f6b1e352b"
size = 4592420

[install]
entry = "gx_mbreverb.lv2/manifest.ttl"
