schema = 1
id = "lv2.gxmbreverb"
name = "gx_mbreverb"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "Guitarix"
tags = ["Reverb","Filter"]
description = "gx_mbreverb applies reverberation across multiple frequency bands to create spectrally shaped ambience."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxmbreverb/1.0.0.zip"
sha256 = "8604c74401cca9f3d52a7047a0fac725e8292170812dfc7287e626ea5c7b686f"
size = 4592420

[install]
entry = "gx_mbreverb.lv2/manifest.ttl"
