schema = 1
id = "lv2.gxscream"
name = "gx_scream"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "Guitarix"
tags = ["Distortion"]
description = "gx_scream adds overdriven clipping and harmonics for an aggressive, sustained instrument tone."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxscream/1.0.0.zip"
sha256 = "e13ec48acb36b3ef31bd3f36f6fb8d69ee4abdd617b5c39c69f5e39ec05125f1"
size = 4365834

[install]
entry = "gx_scream.lv2/manifest.ttl"
