schema = 1
id = "lv2.gxscream"
name = "gx_scream"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "Guitarix"
tags = ["Distortion"]
description = "gx_scream adds overdriven clipping and harmonics for an aggressive, sustained instrument tone."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxscream/1.0.0.zip"
sha256 = "e36160fcdf5db454c5922e13beec35ec8a385fd02867b943ff3287d538828d82"
size = 4365833

[install]
entry = "gx_scream.lv2/manifest.ttl"
