schema = 1
id = "jsfx.tukan.sumthing"
name = "SumThing (Tukan).jsfx"
version = "1.0.0"
format = "jsfx"
arch = ["arm64-v8a"]
manufacturer = "TukanStudios"
tags = ["jsfx"]
description = "SumThing (Tukan)"
license = "custom"

[payload]
kind = "files"
size = 51088

[[payload.files]]
url = "https://raw.githubusercontent.com/TukanStudios/TUKAN_STUDIOS_PLUGINS/e400035bb4c02bf95c1adbef803cba2e4b6b36b5/SumThing%20(Tukan)"
sha256 = "2da8286234404b226d83a3dcf891fe742060db4453a2888bd355a0dbd17ec6a2"
size = 51088
path = "SumThing (Tukan).jsfx"

[install]
entry = "SumThing (Tukan).jsfx"
