schema = 1
id = "lv2.gxcstb"
name = "gx_cstb"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "Guitarix"
tags = ["Distortion"]
description = "gx_cstb provides pedal-style distortion for adding clipping, grit, and harmonic density to instruments."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxcstb/1.0.0.zip"
sha256 = "03e89c968196c9465ecf930a2c1314169fdb22281c534067a20eb18b5e481582"
size = 4857305

[install]
entry = "gx_cstb.lv2/manifest.ttl"
