schema = 1
id = "jsfx.reaper.butterworth24db"
name = "Butterworth 4-Pole Filter"
version = "1.0.0"
format = "jsfx"
arch = ["arm64-v8a"]
manufacturer = "Liteon"
tags = ["jsfx","filter","multimode"]
description = "Butterworth 4-Pole Filter"
license = "GPL"

[payload]
kind = "file"
url = "../../payload/jsfx.reaper.butterworth24db/butterworth24db.jsfx"
sha256 = "35e435e9f24c1c404427455615c8e9d0851292ba03f4948014e9b396d5a024a9"
size = 4853

[install]
entry = "butterworth24db.jsfx"
