schema = 1
id = "lv2.gxbottlerocket"
name = "GxBottleRocket"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "GxPlugins"
tags = ["Distortion"]
description = "Analogue simulation of a tube preamp."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxbottlerocket/1.0.0.zip"
sha256 = "8ab07ef9a62912878843c77401e2e89f2954889361e3a18e86d29867d5da31fb"
size = 1131505

[install]
entry = "GxBottleRocket.lv2/manifest.ttl"
