schema = 1
id = "lv2.gxbottlerocket"
name = "GxBottleRocket"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "GxPlugins"
tags = ["Distortion"]
description = "Analogue simulation of a tube preamp."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxbottlerocket/1.0.0.zip"
sha256 = "54a08b1b85f71fc0112615b1149d9eda2b4e3206708ccc627ea8639f816d3cb2"
size = 1131506

[install]
entry = "GxBottleRocket.lv2/manifest.ttl"
