schema = 1
id = "jsfx.joep.saikemultispectralanalyzer-mk2"
name = "SaikeMultiSpectralAnalyzer_MK2"
version = "1.6"
format = "jsfx"
arch = ["arm64-v8a"]
manufacturer = "Joep Vanlier, Trond-Viggo Melssen, Cockos"
source = "https://github.com/JoepVanlier/JSFX"
tags = ["Analyzer"]
description = "SaikeMultiSpectralAnalyzer_MK2 visualizes spectral content to support detailed frequency-balance analysis."
license = "custom"

[payload]
kind = "files"
size = 63115

[[payload.files]]
url = "https://raw.githubusercontent.com/JoepVanlier/JSFX/21bed3ded6de9568d19f1e3da6bd7e0cc270b5ab/SpectrumAnalyzer/SaikeMultiSpectralAnalyzer_MK2.jsfx"
sha256 = "3481de09ac59fbae0be297216fef81100ff7b5ec4933fc3aa55df019e071451d"
size = 63115
path = "SaikeMultiSpectralAnalyzer_MK2.jsfx"

[install]
entry = "SaikeMultiSpectralAnalyzer_MK2.jsfx"
