schema = 1
id = "lv2.gxultracab"
name = "GxUltraCab"
version = "1.0.0"
format = "lv2"
arch = ["arm64-v8a"]
manufacturer = "GxPlugins"
tags = ["Simulator"]
description = "Cabinet simulator Lv2 stereo."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxultracab/1.0.0.zip"
sha256 = "ad2bb7e64ae8cd83d540e7fc66290834cfd0cd3b558ca645fb8b868bb2481b37"
size = 844207

[install]
entry = "GxUltraCab.lv2/manifest.ttl"
