schema = 1
id = "lv2.preamps"
name = "PreAmps"
version = "1.0.0"
format = "lv2"
arch = ["arm64-v8a"]
manufacturer = "brummer10"
tags = ["Mixer"]
description = "Mixer/routing utility."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.preamps/1.0.0.zip"
sha256 = "0349ba8916851ccd1981e66e5af2683178bae4007bd66dadd4c7cb739bf5dd0b"
size = 2628935

[install]
entry = "PreAmps.lv2/manifest.ttl"
