schema = 1
id = "lv2.gxcreammachine"
name = "GxCreamMachine"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "GxPlugins"
tags = ["Amplifier"]
description = "Simulation, based on a tube power amp circuit."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxcreammachine/1.0.0.zip"
sha256 = "35bfbef432fd068967f5dcd91e27b2f11a15ba7cdc54441711f8e4ebe6918cf8"
size = 1501436

[install]
entry = "GxCreamMachine.lv2/manifest.ttl"
