schema = 1
id = "jsfx.reaper.simplelp6db"
source = "https://www.reaper.fm/"
name = "Simple 1-Pole Filter"
version = "1.0.0"
format = "jsfx"
arch = ["arm64-v8a"]
manufacturer = "Liteon"
tags = ["jsfx","filter"]
description = "A simple one-pole low-pass filter gently removes high-frequency content for smoothing and basic tone control."
license = "GPL"

[payload]
kind = "file"
url = "../../payload/jsfx.reaper.simplelp6db/simplelp6db.jsfx"
sha256 = "33b44dc0c21391429daaa6aa2909ac93615f17a27ffc6c43f46d32a461876ba7"
size = 2649

[install]
entry = "simplelp6db.jsfx"
