schema = 1
id = "lv2.gxhornet"
name = "gx_hornet"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "Guitarix"
tags = ["Distortion"]
description = "gx_hornet is a distortion effect for adding clipped bite and harmonic edge to instrument tones."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxhornet/1.0.0.zip"
sha256 = "1bfcfef14431ab45521bfc8e138eebf43da8592129497558a672e8fe61bbce34"
size = 4418771

[install]
entry = "gx_hornet.lv2/manifest.ttl"
