schema = 1
id = "lv2.gxhornet"
name = "gx_hornet"
version = "1.0.0"
format = "lv2"
arch = ["arm64-v8a"]
manufacturer = "Guitarix"
tags = ["Distortion"]
description = "Distortion/overdrive effect."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxhornet/1.0.0.zip"
sha256 = "73bf85de66ea222210f1b9464a72225bdcad40545dd6d8a61cdb48ebc17c67df"
size = 4418774

[install]
entry = "gx_hornet.lv2/manifest.ttl"
