schema = 1
id = "lv2.impulseloader"
name = "ImpulseLoader"
version = "1.0.0"
format = "lv2"
source = "https://github.com/brummer10/ImpulseLoader"
arch = ["arm64-v8a"]
manufacturer = "brummer10"
tags = ["Reverb"]
description = "A simple mono impulse-response loader and convolver for applying speaker, cabinet, or room coloration."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.impulseloader/1.0.0.zip"
sha256 = "54a2e3251369df68aad0e1869b34c49f648706629b9271ea77898412367a1714"
size = 1287103

[install]
entry = "ImpulseLoader.lv2/manifest.ttl"
