schema = 1
id = "lv2.gxbarkgraphiceq"
name = "gx_barkgraphiceq"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "Guitarix"
tags = ["EQ"]
description = "A Graphic Equalizer with Bark frequency scale."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxbarkgraphiceq/1.0.0.zip"
sha256 = "44debbaeaa4ca0d15a44cbc2e875f0da2e0ff7a4c445ac61dbc6c917d2a0e173"
size = 4278166

[install]
entry = "gx_barkgraphiceq.lv2/manifest.ttl"
