schema = 1
id = "jsfx.sonic.quadracom"
name = "QuadraCom.jsfx"
version = "1.0"
format = "jsfx"
arch = ["arm64-v8a"]
manufacturer = "SonicAnomaly"
tags = ["jsfx"]
description = "QuadraCom"
license = "custom"

[payload]
kind = "files"
size = 494805

[[payload.files]]
url = "https://raw.githubusercontent.com/Sonic-Anomaly/Sonic-Anomaly-JSFX/f14cef59b86bd58c3e1e6a5bf982ff71c302443f/Plugins/QuadraCom.jsfx"
sha256 = "3390c04d18a347cbb6257dc66e490923eff39fd5bac3460d8f11b6bc49426d9f"
size = 26558
path = "QuadraCom.jsfx"

[[payload.files]]
url = "https://raw.githubusercontent.com/Sonic-Anomaly/Sonic-Anomaly-JSFX/f14cef59b86bd58c3e1e6a5bf982ff71c302443f/Plugins/quadracom_gfx/bg.png"
sha256 = "425807106e2c13bf75d45964346b3f5b1aa5e9d3ffbe8d171bc955cfbedc18ac"
size = 67067
path = "quadracom_gfx/bg.png"

[[payload.files]]
url = "https://raw.githubusercontent.com/Sonic-Anomaly/Sonic-Anomaly-JSFX/f14cef59b86bd58c3e1e6a5bf982ff71c302443f/Plugins/quadracom_gfx/sliderknob.png"
sha256 = "ca35eb295af501e39b31db8d832cc8c1ee5d6cd74c3d4bda51e9f42adc291cb5"
size = 357
path = "quadracom_gfx/sliderknob.png"

[[payload.files]]
url = "https://raw.githubusercontent.com/Sonic-Anomaly/Sonic-Anomaly-JSFX/f14cef59b86bd58c3e1e6a5bf982ff71c302443f/Plugins/docs/QuadraCom.pdf"
sha256 = "0241fcd811e955ce3f8db054d1a83b40ec6fe1d66e61f65e3c3555d2f6c0a1d1"
size = 400823
path = "docs/QuadraCom.pdf"

[install]
entry = "QuadraCom.jsfx"
