schema = 1
id = "lv2.gxcolwah"
name = "gx_colwah"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "Guitarix"
tags = ["Filter","Modulation"]
description = "gx_colwah creates wah-style tonal movement by sweeping a resonant filter across the signal."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxcolwah/1.0.0.zip"
sha256 = "bd4e39843813edee8fc18c8af7f59bc3bfa29a8bf62b1ccf64bdf6b7cf9e0291"
size = 3483561

[install]
entry = "gx_colwah.lv2/manifest.ttl"
