schema = 1
id = "lv2.aidax"
name = "AIDA-X"
version = "1.0.0"
format = "lv2"
arch = ["arm64-v8a"]
manufacturer = "Aida DSP"
tags = ["Simulator"]
description = "Simple loader for neural models using RTNeural inference engine."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.aidax/1.0.0.zip"
sha256 = "7311af398a5d26219d0cb4cccd3c6f026f9eb56f98f420296ea400c5e28cc945"
size = 5557879

[install]
entry = "AIDA-X.lv2/manifest.ttl"
