schema = 1
id = "lv2.aidax"
name = "AIDA-X"
version = "1.0.0"
format = "lv2"
source = "https://github.com/AidaDSP/AIDA-X"
arch = ["arm64-v8a"]
manufacturer = "Aida DSP"
tags = ["Simulator"]
description = "Simple loader for neural models using RTNeural inference engine."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.aidax/1.0.0.zip"
sha256 = "f1175ff110c96880cce3b2913362bc4de76086ce5d1b86cf036c59c08df99205"
size = 5557022

[install]
entry = "AIDA-X.lv2/manifest.ttl"
