schema = 1
id = "lv2.gxfuzzface"
name = "gx_fuzzface"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "Guitarix"
tags = ["Distortion","Saturation"]
description = "gx_fuzzface simulates a classic fuzz-style pedal for saturated, sustaining guitar distortion."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxfuzzface/1.0.0.zip"
sha256 = "0fb169a47a13ce1a8b5ced56315f6e085e037c76df3a3961099ec410c5b27c09"
size = 4432700

[install]
entry = "gx_fuzzface.lv2/manifest.ttl"
