schema = 1
id = "lv2.gxdigitaldelayst"
name = "gx_digital_delay_st"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "Guitarix"
tags = ["Delay","Stereo"]
description = "gx_digital_delay_st generates digital echo repeats while preserving or creating a stereo presentation."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxdigitaldelayst/1.0.0.zip"
sha256 = "95c57fc4debda99b9a8004027b3e3e8587c9d520cefe2ecf3d5faa9f1846860a"
size = 5201616

[install]
entry = "gx_digital_delay_st.lv2/manifest.ttl"
