schema = 1
id = "native.nnaga-filter"
name = "NNAGA Filter"
version = "1.0.1"
format = "native"
source = "https://github.com/patlach42/nnaga-native-plugin-sdk"
arch = ["arm64-v8a"]
manufacturer = "NNAGA"
tags = ["Filter","Stereo","Native"]
description = "Stereo zero-latency low-pass or high-pass state-variable filter with resonant Q control."
license = "MIT"

[payload]
kind = "archive"
url = "../../payload/native.nnaga-filter/1.0.1.zip"
sha256 = "9ea70d8667588f224d934d7378240f6cfcb5a9b2a27ce7734dfa8571b6786f9f"
size = 17697

[install]
entry = "arm64-v8a/libnnaga_plugin_filter.so"
