schema = 1
id = "native.nnaga-filter"
name = "NNAGA Filter"
version = "1.0.0"
format = "native"
source = "https://github.com/patlach42/nnaga-native-plugin-sdk"
arch = ["arm64-v8a"]
manufacturer = "NNAGA"
tags = ["Filter","Stereo","Native"]
description = "Stereo zero-latency low-pass or high-pass state-variable filter with resonant Q control."
license = "MIT"

[payload]
kind = "archive"
url = "../../payload/native.nnaga-filter/1.0.0.zip"
sha256 = "e8c8469a529e3a2c36e26c2f3cd796ab4359c74e8cb38e22770bcafe948601dd"
size = 17254

[install]
entry = "arm64-v8a/libnnaga_plugin_filter.so"
