schema = 1
id = "jsfx.tilr.time1"
name = "time1"
version = "1.1.5"
format = "jsfx"
arch = ["arm64-v8a"]
manufacturer = "tilr"
tags = ["jsfx", "delay"]
source = "https://github.com/tiagolr/tilr_jsfx"
description = "A time-based effect for creating controllable echoes, repeats, and temporal modulation."
license = "custom"

[payload]
kind = "files"
size = 1657279

[[payload.files]]
url = "https://raw.githubusercontent.com/tiagolr/tilr_jsfx/3ad1f16c0c974483e1a7e29d507d6a8c43accd0f/Modulation/time1.jsfx"
sha256 = "b6c83dd6dde827e5205e1d697448c2ad26c63085aaa6deeb5ef313d9cdf2b448"
size = 23789
path = "time1.jsfx"

[[payload.files]]
url = "https://raw.githubusercontent.com/tiagolr/tilr_jsfx/3ad1f16c0c974483e1a7e29d507d6a8c43accd0f/Modulation/time1.jsfx.RPL"
sha256 = "f9aa3a9ea834c3f02f98b89a67b6bd17646da5e8a90861f1d367252d6f7fbaee"
size = 1598334
path = "time1.jsfx.RPL"

[[payload.files]]
url = "https://raw.githubusercontent.com/tiagolr/tilr_jsfx/3ad1f16c0c974483e1a7e29d507d6a8c43accd0f/Modulation/time1/time.array.jsfx-inc"
sha256 = "4ade80a551384328629078a8caf18b21e732b0d7f464e86363d3ffe1656d9d20"
size = 6004
path = "time1/time.array.jsfx-inc"

[[payload.files]]
url = "https://raw.githubusercontent.com/tiagolr/tilr_jsfx/3ad1f16c0c974483e1a7e29d507d6a8c43accd0f/Modulation/time1/time.curvelib.jsfx-inc"
sha256 = "4856a15b4b566b2d0442e7840de320c03db27ff546a841b63c9025140e6170b9"
size = 10585
path = "time1/time.curvelib.jsfx-inc"

[[payload.files]]
url = "https://raw.githubusercontent.com/tiagolr/tilr_jsfx/3ad1f16c0c974483e1a7e29d507d6a8c43accd0f/Modulation/time1/time.delay.jsfx-inc"
sha256 = "4d2b78be16d47e129e22b3ceaa69e94098e5201370e0ed1b62665b59a08e778c"
size = 17554
path = "time1/time.delay.jsfx-inc"

[[payload.files]]
url = "https://raw.githubusercontent.com/tiagolr/tilr_jsfx/3ad1f16c0c974483e1a7e29d507d6a8c43accd0f/Modulation/time1/time.mouselib.jsfx-inc"
sha256 = "9aac751ec32b12d2172c0eae06ad27ce582b18c663c91958cf17008f1106062e"
size = 1013
path = "time1/time.mouselib.jsfx-inc"

[install]
entry = "time1.jsfx"
