schema = 1
id = "lv2.gxjcm800prest"
name = "gx_jcm800pre_st"
version = "1.0.0"
format = "lv2"
arch = ["arm64-v8a"]
manufacturer = "Guitarix"
tags = ["Amplifier"]
description = "Amplifier simulation."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxjcm800prest/1.0.0.zip"
sha256 = "36fdaeabfa3facd2705377d1a668d355c44c628b4ccbb03ef41ee3983f0a3673"
size = 4779250

[install]
entry = "gx_jcm800pre_st.lv2/manifest.ttl"
