schema = 1
id = "lv2.gxjcm800prest"
name = "gx_jcm800pre_st"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "Guitarix"
tags = ["Amplifier","Distortion","Stereo"]
description = "gx_jcm800pre_st brings JCM800-style preamp gain and tonal coloration to a stereo signal path."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxjcm800prest/1.0.0.zip"
sha256 = "c9db766228bfa33e19838bb904069e84f95ac5441f2d992ac38d70c418fd3ddf"
size = 4779261

[install]
entry = "gx_jcm800pre_st.lv2/manifest.ttl"
