schema = 1
id = "lv2.gxroomsimulator"
name = "gx_room_simulator"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "Guitarix"
tags = ["Reverb"]
description = "gx_room_simulator creates room-like reflections to give dry audio a defined sense of space."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxroomsimulator/1.0.0.zip"
sha256 = "521c539a54bd24d604660165994684e9574b3bdebd2fcec6aa9ca359cc410ae9"
size = 4729398

[install]
entry = "gx_room_simulator.lv2/manifest.ttl"
