schema = 1
id = "lv2.gxmbdistortion"
name = "gx_mbdistortion"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "Guitarix"
tags = ["Distortion","Saturation"]
description = "gx_mbdistortion applies distortion across multiple frequency bands for spectrally shaped clipping."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxmbdistortion/1.0.0.zip"
sha256 = "5eb8f7c79b23b79612160d65f9dca4ca5f081cf83a9be3027d9fabaabd4a3158"
size = 4949552

[install]
entry = "gx_mbdistortion.lv2/manifest.ttl"
