schema = 1
id = "lv2.gxmbdistortion"
name = "gx_mbdistortion"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "Guitarix"
tags = ["Distortion","Saturation"]
description = "gx_mbdistortion applies distortion across multiple frequency bands for spectrally shaped clipping."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxmbdistortion/1.0.0.zip"
sha256 = "983bfe26455d4972431f9d98c563b5b01e4ad8a9689eace5614866e3fb1425e4"
size = 4949555

[install]
entry = "gx_mbdistortion.lv2/manifest.ttl"
