schema = 1
id = "lv2.gxfuzz"
name = "gx_fuzz"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "Guitarix"
tags = ["Distortion"]
description = "A fuzz processor for producing dense, heavily clipped sustain with pronounced harmonic texture."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxfuzz/1.0.0.zip"
sha256 = "4d627731f10a536177ce138f28c6e17c7c8154d2455a1bbaa917c9dc267ec575"
size = 4523280

[install]
entry = "gx_fuzz.lv2/manifest.ttl"
