schema = 1
id = "lv2.gxsd1"
name = "GxSD1"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "GxPlugins"
tags = ["Distortion"]
description = "Super Overdrive pedal simulation."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxsd1/1.0.0.zip"
sha256 = "f7a1465a53b0aece2c2cb2257502381913baf034eebf8e5bcbc7c76837608aa8"
size = 1402251

[install]
entry = "GxSD1.lv2/manifest.ttl"
