schema = 1
id = "lv2.metaltone"
name = "MetalTone"
version = "1.0.0"
format = "lv2"
source = "https://github.com/brummer10/MetalTone"
arch = ["arm64-v8a"]
manufacturer = "brummer10"
tags = ["Distortion"]
description = "High-gain distortion with an advanced EQ, inspired by the BOSS MT-2 Metal Zone."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.metaltone/1.0.0.zip"
sha256 = "a4261ad2d4fd41d55c0f2871ad736e816dffd89c18ba9c3c577dbb017148e5a7"
size = 1631926

[install]
entry = "MetalTone.lv2/manifest.ttl"
