schema = 1
id = "lv2.metaltone"
name = "MetalTone"
version = "1.0.0"
format = "lv2"
source = "https://github.com/brummer10/MetalTone"
arch = ["arm64-v8a"]
manufacturer = "brummer10"
tags = ["Distortion"]
description = "High-gain distortion with an advanced EQ, inspired by the BOSS MT-2 Metal Zone."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.metaltone/1.0.0.zip"
sha256 = "bdfdb150378e47e3def8ea31cdace4bdc2021ab1074bb56fdfcc2623960fe3e9"
size = 1631925

[install]
entry = "MetalTone.lv2/manifest.ttl"
