schema = 1
id = "jsfx.jozmac.jm-fx-delay-thiran"
name = "JM_fx_Delay_Thiran.jsfx"
version = "1.0"
format = "jsfx"
arch = ["arm64-v8a"]
manufacturer = "Jozef Mackowiak"
tags = ["jsfx"]
description = "Thiran Delay [JM]"
license = "custom"

[payload]
kind = "files"
size = 41036

[[payload.files]]
url = "https://raw.githubusercontent.com/jozmac/reapack-jm/4f507485554c90dcb6a3670058a8f4812c851518/Effects/JM_fx_Delay_Thiran.jsfx"
sha256 = "be5aa110a660a2b8cc0cd124cb452d565cd9e3d6a17275ae0038c53067a13bd3"
size = 10440
path = "JM_fx_Delay_Thiran.jsfx"

[[payload.files]]
url = "https://raw.githubusercontent.com/jozmac/reapack-jm/4f507485554c90dcb6a3670058a8f4812c851518/ThirdParty/Tale/lfo.jsfx-inc"
sha256 = "90481162c2fa62cba3f11ba3fe0a9e106b8e90bcd463c3764e3666334deed034"
size = 30596
path = "Tale/lfo.jsfx-inc"

[install]
entry = "JM_fx_Delay_Thiran.jsfx"
