schema = 1
id = "jsfx.jozmac.jm-temp-stft-based-complex"
name = "JM_temp_STFT-Based_Complex"
version = "1.0"
format = "jsfx"
arch = ["arm64-v8a"]
manufacturer = "Jozef Mackowiak"
source = "https://github.com/jozmac/reapack-jm"
tags = ["Analyzer","Utility"]
description = "An experimental STFT utility for working with the complex-valued spectral representation of audio."
license = "custom"

[payload]
kind = "files"
size = 30019

[[payload.files]]
url = "https://raw.githubusercontent.com/jozmac/reapack-jm/4f507485554c90dcb6a3670058a8f4812c851518/Effects/JM_temp_STFT-Based_Complex.jsfx"
sha256 = "14b0931934b9f0d2b8c563ff150ba98d676f550b7284227263f3884df982fdd8"
size = 6279
path = "JM_temp_STFT-Based_Complex.jsfx"

[[payload.files]]
url = "https://raw.githubusercontent.com/jozmac/reapack-jm/4f507485554c90dcb6a3670058a8f4812c851518/ThirdParty/Tale/window.jsfx-inc"
sha256 = "ec0ca22629777f5838f7e484c00ec7ab580be50f19de4a76ab46400426281962"
size = 15108
path = "Tale/window.jsfx-inc"

[[payload.files]]
url = "https://raw.githubusercontent.com/jozmac/reapack-jm/4f507485554c90dcb6a3670058a8f4812c851518/ThirdParty/Tale/complex.jsfx-inc"
sha256 = "73c92fd28398fdabb4dfecf592e910876dcc7392b9f4c11dfe44a0fda1fa28eb"
size = 8632
path = "Tale/complex.jsfx-inc"

[install]
entry = "JM_temp_STFT-Based_Complex.jsfx"
