schema = 1
id = "lv2.gxmbdelay"
name = "gx_mbdelay"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "Guitarix"
tags = ["Delay","Filter"]
description = "gx_mbdelay creates frequency-dependent echoes by applying delay processing across multiple bands."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxmbdelay/1.0.0.zip"
sha256 = "917823c4a4249f9e1e379d3051f42b8640d71468de7e430f64184ab832d199e9"
size = 4622551

[install]
entry = "gx_mbdelay.lv2/manifest.ttl"
