schema = 1
id = "lv2.gxsd2lead"
name = "GxSD2Lead"
version = "1.0.0"
format = "lv2"
arch = ["arm64-v8a"]
manufacturer = "GxPlugins"
tags = ["Distortion"]
description = "SD2 overdirve pedal simulation."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxsd2lead/1.0.0.zip"
sha256 = "899d6f9e3c951b985d1f0ccbfe05590154a361f516f00cba19af2433746fe7f0"
size = 1664064

[install]
entry = "GxSD2Lead.lv2/manifest.ttl"
