schema = 1
id = "lv2.gxsd2lead"
name = "GxSD2Lead"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "GxPlugins"
tags = ["Distortion"]
description = "SD2 overdirve pedal simulation."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxsd2lead/1.0.0.zip"
sha256 = "6aaa42a82b75c5e0995df9c187128a216d07b36ac7093f4d16acbfdd3a6ba12b"
size = 1664062

[install]
entry = "GxSD2Lead.lv2/manifest.ttl"
