schema = 1
id = "lv2.gxstudiopre"
name = "gx_studiopre"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "Guitarix"
tags = ["Simulator"]
description = "Alembic-style tube studio preamp."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxstudiopre/1.0.0.zip"
sha256 = "685f704e3b571b4d216bedaf1ac401b8846c89d8ae9348f8aaaceaa629d9044f"
size = 4567779

[install]
entry = "gx_studiopre.lv2/manifest.ttl"
