schema = 1
id = "lv2.gxstudiopre"
name = "gx_studiopre"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "Guitarix"
tags = ["Simulator"]
description = "Alembic-style tube studio preamp."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxstudiopre/1.0.0.zip"
sha256 = "66d2b362b36eb5df99b433649ce317e7a5864987e1ba7a1bc1dd3fa87c59e08d"
size = 4567777

[install]
entry = "gx_studiopre.lv2/manifest.ttl"
