schema = 1
id = "jsfx.tukan.sequence"
name = "Sequence (Tukan)"
version = "1.0.0"
format = "jsfx"
arch = ["arm64-v8a"]
manufacturer = "TukanStudios"
tags = ["Synth"]
source = "https://github.com/TukanStudios/TUKAN_STUDIOS_PLUGINS"
description = "Sequence is a synthesizer instrument for creating patterned electronic musical parts."
license = "custom"

[payload]
kind = "files"
size = 173515

[[payload.files]]
url = "https://raw.githubusercontent.com/TukanStudios/TUKAN_STUDIOS_PLUGINS/e400035bb4c02bf95c1adbef803cba2e4b6b36b5/Sequence%20(Tukan)"
sha256 = "c8738f15caec015123353715cb4139fe1695a5e8f2f1392e7e22219ee4738e89"
size = 140732
path = "Sequence (Tukan).jsfx"

[[payload.files]]
url = "https://raw.githubusercontent.com/TukanStudios/TUKAN_STUDIOS_PLUGINS/e400035bb4c02bf95c1adbef803cba2e4b6b36b5/SynthAdd/tk_lib.jsfx-inc"
sha256 = "013d71adf0bc9e6adbdfdb1253fd0041e8578af5811506a3b65913384cc59854"
size = 32783
path = "SynthAdd/tk_lib.jsfx-inc"

[install]
entry = "Sequence (Tukan).jsfx"
