schema = 1
id = "jsfx.joep.saike-stereo-bub-iii"
name = "Saike Stereo Bub III.jsfx"
version = "0.08"
format = "jsfx"
arch = ["arm64-v8a"]
manufacturer = "Joep Vanlier"
tags = ["jsfx"]
description = "Saike Stereo Bub III Stereoizer"
license = "custom"

[payload]
kind = "files"
size = 18451

[[payload.files]]
url = "https://raw.githubusercontent.com/JoepVanlier/JSFX/36753944d642560f26b6480fc7f49431953ca686/Basics/Saike%20Stereo%20Bub%20III.jsfx"
sha256 = "5da4779acef15ec4dae3a620ad1b7881426e8dc34eccc1d994b51ef52fd042e1"
size = 18451
path = "Saike Stereo Bub III.jsfx"

[install]
entry = "Saike Stereo Bub III.jsfx"
