schema = 1
id = "jsfx.joep.saike-superspreaderclone"
name = "Saike SuperSpreaderClone.jsfx"
version = "0.09"
format = "jsfx"
arch = ["arm64-v8a"]
manufacturer = "Original code by lkjb, basic port by Saike (Joep Vanlier)"
tags = ["jsfx"]
description = "Super Spreader"
license = "custom"

[payload]
kind = "files"
size = 15311

[[payload.files]]
url = "https://raw.githubusercontent.com/JoepVanlier/JSFX/edcc0a619cc7fe90fe14996f68a34a5775e033ff/Basics/Saike%20SuperSpreaderClone.jsfx"
sha256 = "5577137a10e3c0e2ce954eee4a96fe50e11193acc9b5ca4f6873f31bfeb2347e"
size = 15311
path = "Saike SuperSpreaderClone.jsfx"

[install]
entry = "Saike SuperSpreaderClone.jsfx"
