schema = 1
id = "lv2.gxsusta"
name = "gx_susta"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "Guitarix"
tags = ["Distortion","Saturation"]
description = "gx_susta uses driven coloration to increase perceived sustain and density in instrument signals."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxsusta/1.0.0.zip"
sha256 = "78ffc78f331273e0c6725791117ec634012bbe5f0c8c1b77aa66e831033bb184"
size = 4477195

[install]
entry = "gx_susta.lv2/manifest.ttl"
