schema = 1
id = "lv2.gxmole"
name = "gx_mole"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "Guitarix"
tags = ["Filter"]
description = "gx_mole is a tone filter that reshapes an instrument signal by emphasizing or attenuating frequencies."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxmole/1.0.0.zip"
sha256 = "176dc30bc6ae2775851e4c031f6c0780881a47eeee7c465c1045711563339bba"
size = 3488760

[install]
entry = "gx_mole.lv2/manifest.ttl"
