schema = 1
id = "lv2.gxts9"
name = "gxts9"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "Guitarix"
tags = ["Distortion"]
description = "Analog distortion emulation of the classic Ibanez TS-9 (*)."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxts9/1.0.0.zip"
sha256 = "c60e5b8599d569ff3c277a1c748a70cf448fd0ef6d25af251b2dcfebb25d3641"
size = 3504111

[install]
entry = "gxts9.lv2/manifest.ttl"
