schema = 1
id = "jsfx.joep.tight-compressor"
name = "Tight_Compressor.jsfx"
version = "0.23"
format = "jsfx"
arch = ["arm64-v8a"]
manufacturer = "Joep Vanlier"
tags = ["jsfx"]
description = "Saike Tight Compressor"
license = "custom"

[payload]
kind = "files"
size = 142123

[[payload.files]]
url = "https://raw.githubusercontent.com/JoepVanlier/JSFX/573b3f55efb3983efb9da99a3354776e7d4ab170/Basics/Tight_Compressor.jsfx"
sha256 = "c8e9264c6a634eb1bb81eab69f30fd32cc7e30eedcf933fbcbcf10181b2f3758"
size = 15170
path = "Tight_Compressor.jsfx"

[[payload.files]]
url = "https://raw.githubusercontent.com/JoepVanlier/JSFX/573b3f55efb3983efb9da99a3354776e7d4ab170/Basics/saike_upsamplers.jsfx-inc"
sha256 = "c254b307e71bc409106230ca26907f0f0eaba9522b7ca76139022bb427811a66"
size = 126953
path = "saike_upsamplers.jsfx-inc"

[install]
entry = "Tight_Compressor.jsfx"
