schema = 1
id = "lv2.gxuvox720k"
name = "GxUVox720k"
version = "1.0.0"
format = "lv2"
arch = ["arm64-v8a"]
manufacturer = "GxPlugins"
tags = ["Amplifier"]
description = "Analog simulation of the UniVox (*) 720k solid state amp as."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxuvox720k/1.0.0.zip"
sha256 = "ffbb298545c010372a0bcd54a05fb6c08c57f7c1ba999b257b084eb3b1e7e8ca"
size = 1546989

[install]
entry = "GxUVox720k.lv2/manifest.ttl"
