schema = 1
id = "lv2.gxuvox720k"
name = "GxUVox720k"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "GxPlugins"
tags = ["Amplifier"]
description = "Solid-state amplifier simulation inspired by the Univox 720K, adding vintage gain and tonal coloration to guitar signals."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxuvox720k/1.0.0.zip"
sha256 = "0a0f341b9842ae957b87a247e396a1c25b2461af7ebf9c854c41afa7985ac064"
size = 1546988

[install]
entry = "GxUVox720k.lv2/manifest.ttl"
