schema = 1
id = "lv2.gxmbecho"
name = "gx_mbecho"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "Guitarix"
tags = ["Delay","Filter"]
description = "gx_mbecho produces band-dependent echo effects by processing delayed repeats across multiple frequency ranges."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxmbecho/1.0.0.zip"
sha256 = "a7052885c79c7ecc30cb1d06f8d399c1076b0050dd8e22f4d0baef534080bfee"
size = 4555941

[install]
entry = "gx_mbecho.lv2/manifest.ttl"
