schema = 1
id = "jsfx.jozmac.jm-fx-filter-median"
name = "JM_fx_Filter_Median.jsfx"
version = "1.0"
format = "jsfx"
arch = ["arm64-v8a"]
manufacturer = "Jozef Mackowiak"
tags = ["jsfx"]
description = "Median Filter [JM]"
license = "custom"

[payload]
kind = "files"
size = 3056

[[payload.files]]
url = "https://raw.githubusercontent.com/jozmac/reapack-jm/4f507485554c90dcb6a3670058a8f4812c851518/Effects/JM_fx_Filter_Median.jsfx"
sha256 = "a924a6d78dcedc5ddedd44b910c2b7758fcf0e928c09356d63a3c5bc8bebd0b9"
size = 3056
path = "JM_fx_Filter_Median.jsfx"

[install]
entry = "JM_fx_Filter_Median.jsfx"
