schema = 1
id = "jsfx.jozmac.jm-fx-stft-coherent-extractor"
name = "JM_fx_STFT_Coherent_Extractor.jsfx"
version = "1.0"
format = "jsfx"
arch = ["arm64-v8a"]
manufacturer = "Jozef Mackowiak"
tags = ["jsfx"]
description = "STFT Coherent Extractor [JM]"
license = "custom"

[payload]
kind = "files"
size = 20658

[[payload.files]]
url = "https://raw.githubusercontent.com/jozmac/reapack-jm/4f507485554c90dcb6a3670058a8f4812c851518/Effects/JM_fx_STFT_Coherent_Extractor.jsfx"
sha256 = "11cfe99a666825ea47a344e1b394f0dbbda9d4001332204f27a009e7ecda3a3c"
size = 12026
path = "JM_fx_STFT_Coherent_Extractor.jsfx"

[[payload.files]]
url = "https://raw.githubusercontent.com/jozmac/reapack-jm/4f507485554c90dcb6a3670058a8f4812c851518/ThirdParty/Tale/complex.jsfx-inc"
sha256 = "73c92fd28398fdabb4dfecf592e910876dcc7392b9f4c11dfe44a0fda1fa28eb"
size = 8632
path = "Tale/complex.jsfx-inc"

[install]
entry = "JM_fx_STFT_Coherent_Extractor.jsfx"
