schema = 1
id = "lv2.gxtapest"
name = "gxtape_st"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "Guitarix"
tags = ["Filter","Saturation","Stereo"]
description = "gxtape_st applies tape-style filtering and harmonic coloration while retaining stereo processing."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxtapest/1.0.0.zip"
sha256 = "1d33d31d224868adf095497746e00710d900c3df2c9c91f5b3592702fec6f6a0"
size = 3641689

[install]
entry = "gxtape_st.lv2/manifest.ttl"
