schema = 1
id = "lv2.gxtapest"
name = "gxtape_st"
version = "1.0.0"
format = "lv2"
arch = ["arm64-v8a"]
manufacturer = "Guitarix"
tags = ["Filter"]
description = "Filter/tone shaping effect."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxtapest/1.0.0.zip"
sha256 = "eecf191bde0d12ee7e86e151fbd68d5bb01d1aa02969189b2fbef8d74c31d25c"
size = 3641690

[install]
entry = "gxtape_st.lv2/manifest.ttl"
