schema = 1
id = "lv2.gxjcm800pre"
name = "gx_jcm800pre"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "Guitarix"
tags = ["Amplifier","Distortion"]
description = "gx_jcm800pre models a JCM800-style guitar preamplifier for gain and characteristic amp coloration."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxjcm800pre/1.0.0.zip"
sha256 = "a12d963f61cd9df93a0f65595feddcfbd0ce5d4fab2f0021bea01b62f031d653"
size = 4772129

[install]
entry = "gx_jcm800pre.lv2/manifest.ttl"
