schema = 1
id = "lv2.gxjcm800pre"
name = "gx_jcm800pre"
version = "1.0.0"
format = "lv2"
arch = ["arm64-v8a"]
manufacturer = "Guitarix"
tags = ["Amplifier"]
description = "Amplifier simulation."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxjcm800pre/1.0.0.zip"
sha256 = "bd95ccb9a5905e0fad936e4818420c71b6cbdb43d8d18858c70ceac114fe3a27"
size = 4772171

[install]
entry = "gx_jcm800pre.lv2/manifest.ttl"
