schema = 1
id = "jsfx.tilr.distr"
name = "distr.jsfx"
version = "1.0.3"
format = "jsfx"
arch = ["arm64-v8a"]
manufacturer = "tilr"
tags = ["jsfx"]
description = "DIST-R"
license = "custom"

[payload]
kind = "files"
size = 175137

[[payload.files]]
url = "https://raw.githubusercontent.com/tiagolr/tilr_jsfx/8379da177843b130bcd828cb9a0bb87ce8a508e0/Modulation/distr.jsfx"
sha256 = "29213b6c1cc1088b2160492ae03dab4d4ffc018f3556636bf247c73cc5ec870a"
size = 26356
path = "distr.jsfx"

[[payload.files]]
url = "https://raw.githubusercontent.com/tiagolr/tilr_jsfx/8379da177843b130bcd828cb9a0bb87ce8a508e0/Modulation/distr/distr.squashman_upsamplers.jsfx-inc"
sha256 = "ceb2766663f082fbbdb78c9fe33c21001afb744f613ec19c9bc8241cc3769902"
size = 128029
path = "distr/distr.squashman_upsamplers.jsfx-inc"

[[payload.files]]
url = "https://raw.githubusercontent.com/tiagolr/tilr_jsfx/8379da177843b130bcd828cb9a0bb87ce8a508e0/Modulation/distr/distr.curvelib.jsfx-inc"
sha256 = "d0de9bc307d171e258306343f7f03420f4e278b2f447370e1e6969e3d08b8c0f"
size = 10463
path = "distr/distr.curvelib.jsfx-inc"

[[payload.files]]
url = "https://raw.githubusercontent.com/tiagolr/tilr_jsfx/8379da177843b130bcd828cb9a0bb87ce8a508e0/Modulation/distr/distr.mouselib.jsfx-inc"
sha256 = "9aac751ec32b12d2172c0eae06ad27ce582b18c663c91958cf17008f1106062e"
size = 1013
path = "distr/distr.mouselib.jsfx-inc"

[[payload.files]]
url = "https://raw.githubusercontent.com/tiagolr/tilr_jsfx/8379da177843b130bcd828cb9a0bb87ce8a508e0/Modulation/distr/distr.array.jsfx-inc"
sha256 = "4ade80a551384328629078a8caf18b21e732b0d7f464e86363d3ffe1656d9d20"
size = 6004
path = "distr/distr.array.jsfx-inc"

[[payload.files]]
url = "https://raw.githubusercontent.com/tiagolr/tilr_jsfx/8379da177843b130bcd828cb9a0bb87ce8a508e0/Modulation/distr/distr.distortions.jsfx-inc"
sha256 = "8ebbbec6b17b4bd82182d611bb2bf4a53002222363a7be0b4e51bbc7658d573f"
size = 3272
path = "distr/distr.distortions.jsfx-inc"

[install]
entry = "distr.jsfx"
