schema = 1
id = "lv2.gxaxisface"
name = "GxAxisFace"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "GxPlugins"
tags = ["Distortion"]
description = "Simulation of the Axis Face Silicon Pedal."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxaxisface/1.0.0.zip"
sha256 = "aceb1f5df8d8d6acce19bd1dbaca712eb443a6f9c2d50a4c0e3875b9dd67aed5"
size = 1799643

[install]
entry = "GxAxisFace.lv2/manifest.ttl"
