schema = 1
id = "lv2.gxaxisface"
name = "GxAxisFace"
version = "1.0.0"
format = "lv2"
arch = ["arm64-v8a"]
manufacturer = "GxPlugins"
tags = ["Distortion"]
description = "Simulation of the Axis Face Silicon Pedal."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxaxisface/1.0.0.zip"
sha256 = "95229c8afe5dfbf9bf8304ecc2aa2b231c1494f9e283adf6429784eae9d038d4"
size = 1799643

[install]
entry = "GxAxisFace.lv2/manifest.ttl"
