schema = 1
id = "jsfx.joep.wahriffic"
name = "wahriffic.jsfx"
version = "0.04"
format = "jsfx"
arch = ["arm64-v8a"]
manufacturer = "Joep Vanlier"
tags = ["jsfx"]
description = "Saike Wahriffic"
license = "custom"

[payload]
kind = "files"
size = 60395

[[payload.files]]
url = "https://raw.githubusercontent.com/JoepVanlier/JSFX/ae072a7e98acc66f7fc4355ba0f07613b164d33b/Basics/wahriffic.jsfx"
sha256 = "5d72ef84f1b46b5c861a204208d41528921ef246fdd2eae922330bc9db951612"
size = 5635
path = "wahriffic.jsfx"

[[payload.files]]
url = "https://raw.githubusercontent.com/JoepVanlier/JSFX/ae072a7e98acc66f7fc4355ba0f07613b164d33b/Basics/wah_models.jsfx-inc"
sha256 = "53b746d7a1b546782b7431e52a0e1f720aa918d8c6ee595eb130d3fffe692b53"
size = 54760
path = "wah_models.jsfx-inc"

[install]
entry = "wahriffic.jsfx"
