schema = 1
id = "jsfx.jclones.jclones-satchannel"
name = "JClones_SatChannel.jsfx"
version = "1.1.0"
format = "jsfx"
arch = ["arm64-v8a"]
manufacturer = "JClones"
tags = ["jsfx"]
description = "JClones_SatChannel"
license = "custom"

[payload]
kind = "files"
size = 7585

[[payload.files]]
url = "https://raw.githubusercontent.com/JClones/JSFXClones/9486f9cb9bc7b929d8e5db2959db0b97326d1a18/jsfx/JClones_SatChannel.jsfx"
sha256 = "5d4bdd2b504456fa10380b66679028bf25a2e4e6ac99521f9a6ec723d9cffb2a"
size = 7585
path = "JClones_SatChannel.jsfx"

[install]
entry = "JClones_SatChannel.jsfx"
