schema = 1
id = "lv2.gxoc2"
name = "gx_oc_2"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "Guitarix"
tags = ["Pitch"]
description = "gx_oc_2 shifts an instrument signal by octaves to create layered lower or upper-pitched tones."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxoc2/1.0.0.zip"
sha256 = "a935d66bcb69dd76886bd8e3c1fd9dc6acd6d39cbc42b70bd1a5758ce4d2412a"
size = 4466596

[install]
entry = "gx_oc_2.lv2/manifest.ttl"
