schema = 1
id = "lv2.gxoc2"
name = "gx_oc_2"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "Guitarix"
tags = ["Pitch"]
description = "gx_oc_2 shifts an instrument signal by octaves to create layered lower or upper-pitched tones."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxoc2/1.0.0.zip"
sha256 = "f4132bab8c45a7b55eed22c0f3c5cc12f6db12b5598b4d54689be15f128067a5"
size = 4466592

[install]
entry = "gx_oc_2.lv2/manifest.ttl"
