schema = 1
id = "lv2.gxmxrdist"
name = "gx_mxrdist"
version = "1.0.0"
format = "lv2"
arch = ["arm64-v8a"]
manufacturer = "Guitarix"
tags = ["Distortion"]
description = "Distortion/overdrive effect."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxmxrdist/1.0.0.zip"
sha256 = "31f81e91cd77e57f81c303b9749071b6a9eb2f015c2e49a98357c6528673360e"
size = 3483745

[install]
entry = "gx_mxrdist.lv2/manifest.ttl"
