schema = 1
id = "lv2.gxmxrdist"
name = "gx_mxrdist"
version = "1.0.0"
format = "lv2"
source = "https://github.com/djshaji/GxPlugins.lv2.Android"
arch = ["arm64-v8a"]
manufacturer = "Guitarix"
tags = ["Distortion"]
description = "gx_mxrdist applies pedal-style clipping to add grit, sustain, and harmonic edge to instrument signals."
license = "GPL-3.0-or-later"

[payload]
kind = "archive"
url = "../../payload/lv2.gxmxrdist/1.0.0.zip"
sha256 = "c11fda63c364d6dc26458d986a6623254be24c2336f6f813b308c081b2450975"
size = 3483743

[install]
entry = "gx_mxrdist.lv2/manifest.ttl"
